package com.cibr.animal.demo.dao;

import com.cibr.animal.demo.entity.CibrSysTaskBusiness;
import com.cibr.animal.demo.entity.CibrSysTaskBusinessExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface CibrSysTaskBusinessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_task_business
     *
     * @mbggenerated
     */
    int countByExample(CibrSysTaskBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_task_business
     *
     * @mbggenerated
     */
    int deleteByExample(CibrSysTaskBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_task_business
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_task_business
     *
     * @mbggenerated
     */
    int insert(CibrSysTaskBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_task_business
     *
     * @mbggenerated
     */
    int insertSelective(CibrSysTaskBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_task_business
     *
     * @mbggenerated
     */
    List<CibrSysTaskBusiness> selectByExample(CibrSysTaskBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_task_business
     *
     * @mbggenerated
     */
    CibrSysTaskBusiness selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_task_business
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CibrSysTaskBusiness record, @Param("example") CibrSysTaskBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_task_business
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CibrSysTaskBusiness record, @Param("example") CibrSysTaskBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_task_business
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CibrSysTaskBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_task_business
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CibrSysTaskBusiness record);
}