package com.cibr.animal.demo.dao;

import com.cibr.animal.demo.entity.CibrStockDrosophila;
import com.cibr.animal.demo.entity.CibrStockDrosophilaExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface CibrStockDrosophilaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_stock_drosophila
     *
     * @mbggenerated
     */
    int countByExample(CibrStockDrosophilaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_stock_drosophila
     *
     * @mbggenerated
     */
    int deleteByExample(CibrStockDrosophilaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_stock_drosophila
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_stock_drosophila
     *
     * @mbggenerated
     */
    int insert(CibrStockDrosophila record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_stock_drosophila
     *
     * @mbggenerated
     */
    int insertSelective(CibrStockDrosophila record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_stock_drosophila
     *
     * @mbggenerated
     */
    List<CibrStockDrosophila> selectByExample(CibrStockDrosophilaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_stock_drosophila
     *
     * @mbggenerated
     */
    CibrStockDrosophila selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_stock_drosophila
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CibrStockDrosophila record, @Param("example") CibrStockDrosophilaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_stock_drosophila
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CibrStockDrosophila record, @Param("example") CibrStockDrosophilaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_stock_drosophila
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CibrStockDrosophila record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_stock_drosophila
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CibrStockDrosophila record);

    int batchInsert(List<CibrStockDrosophila> list);

    List<CibrStockDrosophila> selectAllStocks(@Param("condition") Map condition);

}