package com.cibr.animal.demo.dao;

import com.cibr.animal.demo.entity.CibrTaskProcessConfirm;
import com.cibr.animal.demo.entity.CibrTaskProcessConfirmExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CibrTaskProcessConfirmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_confirm
     *
     * @mbggenerated
     */
    int countByExample(CibrTaskProcessConfirmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_confirm
     *
     * @mbggenerated
     */
    int deleteByExample(CibrTaskProcessConfirmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_confirm
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_confirm
     *
     * @mbggenerated
     */
    int insert(CibrTaskProcessConfirm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_confirm
     *
     * @mbggenerated
     */
    int insertSelective(CibrTaskProcessConfirm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_confirm
     *
     * @mbggenerated
     */
    List<CibrTaskProcessConfirm> selectByExample(CibrTaskProcessConfirmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_confirm
     *
     * @mbggenerated
     */
    CibrTaskProcessConfirm selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_confirm
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CibrTaskProcessConfirm record, @Param("example") CibrTaskProcessConfirmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_confirm
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CibrTaskProcessConfirm record, @Param("example") CibrTaskProcessConfirmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_confirm
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CibrTaskProcessConfirm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_confirm
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CibrTaskProcessConfirm record);

    int batchInsert(List<CibrTaskProcessConfirm> list);

    int batchUpdate(List<CibrTaskProcessConfirm> list);

    List<CibrTaskProcessConfirm> selectWithCommitNumber(@Param("processId")String processId, @Param("currentStatu")String currentStatu);
}