package com.cibr.animal.demo.dao;

import com.cibr.animal.demo.entity.CibrTaskDetailDrosophila;
import com.cibr.animal.demo.entity.CibrTaskDetailDrosophilaExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CibrTaskDetailDrosophilaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_detail_drosophila
     *
     * @mbggenerated
     */
    int countByExample(CibrTaskDetailDrosophilaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_detail_drosophila
     *
     * @mbggenerated
     */
    int deleteByExample(CibrTaskDetailDrosophilaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_detail_drosophila
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_detail_drosophila
     *
     * @mbggenerated
     */
    int insert(CibrTaskDetailDrosophila record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_detail_drosophila
     *
     * @mbggenerated
     */
    int insertSelective(CibrTaskDetailDrosophila record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_detail_drosophila
     *
     * @mbggenerated
     */
    List<CibrTaskDetailDrosophila> selectByExample(CibrTaskDetailDrosophilaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_detail_drosophila
     *
     * @mbggenerated
     */
    CibrTaskDetailDrosophila selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_detail_drosophila
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CibrTaskDetailDrosophila record, @Param("example") CibrTaskDetailDrosophilaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_detail_drosophila
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CibrTaskDetailDrosophila record, @Param("example") CibrTaskDetailDrosophilaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_detail_drosophila
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CibrTaskDetailDrosophila record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_detail_drosophila
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CibrTaskDetailDrosophila record);

    int batchInsert(List<CibrTaskDetailDrosophila> list);
}