package com.cibr.animal.demo.dao;

import com.cibr.animal.demo.entity.CibrSysMaterial;
import com.cibr.animal.demo.entity.CibrSysMaterialExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface CibrSysMaterialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_material
     *
     * @mbggenerated
     */
    int countByExample(CibrSysMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_material
     *
     * @mbggenerated
     */
    int deleteByExample(CibrSysMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_material
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_material
     *
     * @mbggenerated
     */
    int insert(CibrSysMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_material
     *
     * @mbggenerated
     */
    int insertSelective(CibrSysMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_material
     *
     * @mbggenerated
     */
    List<CibrSysMaterial> selectByExample(CibrSysMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_material
     *
     * @mbggenerated
     */
    CibrSysMaterial selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_material
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CibrSysMaterial record, @Param("example") CibrSysMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_material
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CibrSysMaterial record, @Param("example") CibrSysMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_material
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CibrSysMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_material
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CibrSysMaterial record);

    List<CibrSysMaterial> selectAll(@Param("condition") Map condition);
}