package com.cibr.animal.demo.dao;

import com.cibr.animal.demo.entity.CibrTaskProcessDiystatu;
import com.cibr.animal.demo.entity.CibrTaskProcessDiystatuExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CibrTaskProcessDiystatuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_diystatu
     *
     * @mbggenerated
     */
    int countByExample(CibrTaskProcessDiystatuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_diystatu
     *
     * @mbggenerated
     */
    int deleteByExample(CibrTaskProcessDiystatuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_diystatu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_diystatu
     *
     * @mbggenerated
     */
    int insert(CibrTaskProcessDiystatu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_diystatu
     *
     * @mbggenerated
     */
    int insertSelective(CibrTaskProcessDiystatu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_diystatu
     *
     * @mbggenerated
     */
    List<CibrTaskProcessDiystatu> selectByExample(CibrTaskProcessDiystatuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_diystatu
     *
     * @mbggenerated
     */
    CibrTaskProcessDiystatu selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_diystatu
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CibrTaskProcessDiystatu record, @Param("example") CibrTaskProcessDiystatuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_diystatu
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CibrTaskProcessDiystatu record, @Param("example") CibrTaskProcessDiystatuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_diystatu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CibrTaskProcessDiystatu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_diystatu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CibrTaskProcessDiystatu record);
}