package com.cibr.animal.demo.dao;

import com.cibr.animal.demo.entity.CibrTaskProcessLibrary;
import com.cibr.animal.demo.entity.CibrTaskProcessLibraryExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CibrTaskProcessLibraryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_library
     *
     * @mbggenerated
     */
    int countByExample(CibrTaskProcessLibraryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_library
     *
     * @mbggenerated
     */
    int deleteByExample(CibrTaskProcessLibraryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_library
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_library
     *
     * @mbggenerated
     */
    int insert(CibrTaskProcessLibrary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_library
     *
     * @mbggenerated
     */
    int insertSelective(CibrTaskProcessLibrary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_library
     *
     * @mbggenerated
     */
    List<CibrTaskProcessLibrary> selectByExample(CibrTaskProcessLibraryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_library
     *
     * @mbggenerated
     */
    CibrTaskProcessLibrary selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_library
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CibrTaskProcessLibrary record, @Param("example") CibrTaskProcessLibraryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_library
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CibrTaskProcessLibrary record, @Param("example") CibrTaskProcessLibraryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_library
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CibrTaskProcessLibrary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_library
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CibrTaskProcessLibrary record);

    int batchInsert(List<CibrTaskProcessLibrary> list);

    int batchUpdate(List<CibrTaskProcessLibrary> list);
}