package com.cibr.animal.demo.dao;

import com.cibr.animal.demo.entity.CibrAnimalDrosophila;
import com.cibr.animal.demo.entity.CibrAnimalDrosophilaExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.beans.factory.annotation.Autowired;

import java.util.List;

@Mapper
public interface CibrAnimalDrosophilaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_animal_drosophila
     *
     * @mbggenerated
     */
    int countByExample(CibrAnimalDrosophilaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_animal_drosophila
     *
     * @mbggenerated
     */
    int deleteByExample(CibrAnimalDrosophilaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_animal_drosophila
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_animal_drosophila
     *
     * @mbggenerated
     */
    int insert(CibrAnimalDrosophila record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_animal_drosophila
     *
     * @mbggenerated
     */
    int insertSelective(CibrAnimalDrosophila record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_animal_drosophila
     *
     * @mbggenerated
     */
    List<CibrAnimalDrosophila> selectByExample(CibrAnimalDrosophilaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_animal_drosophila
     *
     * @mbggenerated
     */
    CibrAnimalDrosophila selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_animal_drosophila
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CibrAnimalDrosophila record, @Param("example") CibrAnimalDrosophilaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_animal_drosophila
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CibrAnimalDrosophila record, @Param("example") CibrAnimalDrosophilaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_animal_drosophila
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CibrAnimalDrosophila record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_animal_drosophila
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CibrAnimalDrosophila record);

    List<CibrAnimalDrosophila> selectAllStock();

    List<CibrAnimalDrosophila> selectAll();

    List<CibrAnimalDrosophila> selectAllStockLimit(int currIndex,int pageSize);

    int selectTotalNumber();

    int batchInsert(List<CibrAnimalDrosophila> list);
}