package com.cibr.animal.demo.dao;

import com.cibr.animal.demo.entity.CibrTaskProcessAnalysis;
import com.cibr.animal.demo.entity.CibrTaskProcessAnalysisExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CibrTaskProcessAnalysisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_analysis
     *
     * @mbggenerated
     */
    int countByExample(CibrTaskProcessAnalysisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_analysis
     *
     * @mbggenerated
     */
    int deleteByExample(CibrTaskProcessAnalysisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_analysis
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_analysis
     *
     * @mbggenerated
     */
    int insert(CibrTaskProcessAnalysis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_analysis
     *
     * @mbggenerated
     */
    int insertSelective(CibrTaskProcessAnalysis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_analysis
     *
     * @mbggenerated
     */
    List<CibrTaskProcessAnalysis> selectByExample(CibrTaskProcessAnalysisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_analysis
     *
     * @mbggenerated
     */
    CibrTaskProcessAnalysis selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_analysis
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CibrTaskProcessAnalysis record, @Param("example") CibrTaskProcessAnalysisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_analysis
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CibrTaskProcessAnalysis record, @Param("example") CibrTaskProcessAnalysisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_analysis
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CibrTaskProcessAnalysis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_analysis
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CibrTaskProcessAnalysis record);

    void batchInsert(List<CibrTaskProcessAnalysis> analyses);

    void batchUpdate(List<CibrTaskProcessAnalysis> analyses);
}