package com.cibr.animal.demo.dao;

import com.cibr.animal.demo.entity.CibrTaskPartner;
import com.cibr.animal.demo.entity.CibrTaskPartnerExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CibrTaskPartnerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_partner
     *
     * @mbggenerated
     */
    int countByExample(CibrTaskPartnerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_partner
     *
     * @mbggenerated
     */
    int deleteByExample(CibrTaskPartnerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_partner
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_partner
     *
     * @mbggenerated
     */
    int insert(CibrTaskPartner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_partner
     *
     * @mbggenerated
     */
    int insertSelective(CibrTaskPartner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_partner
     *
     * @mbggenerated
     */
    List<CibrTaskPartner> selectByExample(CibrTaskPartnerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_partner
     *
     * @mbggenerated
     */
    CibrTaskPartner selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_partner
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CibrTaskPartner record, @Param("example") CibrTaskPartnerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_partner
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CibrTaskPartner record, @Param("example") CibrTaskPartnerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_partner
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CibrTaskPartner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_partner
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CibrTaskPartner record);
}