package com.cibr.animal.demo.dao;

import com.cibr.animal.demo.entity.CibrSysUserGroup;
import com.cibr.animal.demo.entity.CibrSysUserGroupExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CibrSysUserGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_user_group
     *
     * @mbggenerated
     */
    int countByExample(CibrSysUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_user_group
     *
     * @mbggenerated
     */
    int deleteByExample(CibrSysUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_user_group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_user_group
     *
     * @mbggenerated
     */
    int insert(CibrSysUserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_user_group
     *
     * @mbggenerated
     */
    int insertSelective(CibrSysUserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_user_group
     *
     * @mbggenerated
     */
    List<CibrSysUserGroup> selectByExample(CibrSysUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_user_group
     *
     * @mbggenerated
     */
    CibrSysUserGroup selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_user_group
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CibrSysUserGroup record, @Param("example") CibrSysUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_user_group
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CibrSysUserGroup record, @Param("example") CibrSysUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_user_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CibrSysUserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_user_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CibrSysUserGroup record);

    List<CibrSysUserGroup> findallgroupsWithUsers();

    void batchUpdate(List<CibrSysUserGroup> groups);
}