package com.cibr.animal.demo.dao;

import com.cibr.animal.demo.entity.CibrBillLib;
import com.cibr.animal.demo.entity.CibrBillLibExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CibrBillLibMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_bill_lib
     *
     * @mbggenerated
     */
    int countByExample(CibrBillLibExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_bill_lib
     *
     * @mbggenerated
     */
    int deleteByExample(CibrBillLibExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_bill_lib
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_bill_lib
     *
     * @mbggenerated
     */
    int insert(CibrBillLib record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_bill_lib
     *
     * @mbggenerated
     */
    int insertSelective(CibrBillLib record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_bill_lib
     *
     * @mbggenerated
     */
    List<CibrBillLib> selectByExample(CibrBillLibExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_bill_lib
     *
     * @mbggenerated
     */
    CibrBillLib selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_bill_lib
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CibrBillLib record, @Param("example") CibrBillLibExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_bill_lib
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CibrBillLib record, @Param("example") CibrBillLibExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_bill_lib
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CibrBillLib record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_bill_lib
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CibrBillLib record);
}