package com.cibr.animal.demo.dao;

import com.cibr.animal.demo.entity.CibrTaskAskDirector;
import com.cibr.animal.demo.entity.CibrTaskAskDirectorExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface CibrTaskAskDirectorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_ask_director
     *
     * @mbggenerated
     */
    int countByExample(CibrTaskAskDirectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_ask_director
     *
     * @mbggenerated
     */
    int deleteByExample(CibrTaskAskDirectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_ask_director
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_ask_director
     *
     * @mbggenerated
     */
    int insert(CibrTaskAskDirector record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_ask_director
     *
     * @mbggenerated
     */
    int insertSelective(CibrTaskAskDirector record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_ask_director
     *
     * @mbggenerated
     */
    List<CibrTaskAskDirector> selectByExample(CibrTaskAskDirectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_ask_director
     *
     * @mbggenerated
     */
    CibrTaskAskDirector selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_ask_director
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CibrTaskAskDirector record, @Param("example") CibrTaskAskDirectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_ask_director
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CibrTaskAskDirector record, @Param("example") CibrTaskAskDirectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_ask_director
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CibrTaskAskDirector record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_ask_director
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CibrTaskAskDirector record);

    int batchInsert(List<CibrTaskAskDirector> list);
}