package com.cibr.animal.demo.dao;

import com.cibr.animal.demo.entity.CibrSysEnvironment;
import com.cibr.animal.demo.entity.CibrSysEnvironmentExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface CibrSysEnvironmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_environment
     *
     * @mbggenerated
     */
    int countByExample(CibrSysEnvironmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_environment
     *
     * @mbggenerated
     */
    int deleteByExample(CibrSysEnvironmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_environment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_environment
     *
     * @mbggenerated
     */
    int insert(CibrSysEnvironment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_environment
     *
     * @mbggenerated
     */
    int insertSelective(CibrSysEnvironment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_environment
     *
     * @mbggenerated
     */
    List<CibrSysEnvironment> selectByExample(CibrSysEnvironmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_environment
     *
     * @mbggenerated
     */
    CibrSysEnvironment selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_environment
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CibrSysEnvironment record, @Param("example") CibrSysEnvironmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_environment
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CibrSysEnvironment record, @Param("example") CibrSysEnvironmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_environment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CibrSysEnvironment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_environment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CibrSysEnvironment record);

    List<CibrSysEnvironment> selectAllRecord();
}