package com.cibr.animal.demo.dao;

import com.cibr.animal.demo.entity.CibrTaskAskDrosophila;
import com.cibr.animal.demo.entity.CibrTaskAskDrosophilaExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CibrTaskAskDrosophilaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_ask_drosophila
     *
     * @mbggenerated
     */
    int countByExample(CibrTaskAskDrosophilaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_ask_drosophila
     *
     * @mbggenerated
     */
    int deleteByExample(CibrTaskAskDrosophilaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_ask_drosophila
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_ask_drosophila
     *
     * @mbggenerated
     */
    int insert(CibrTaskAskDrosophila record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_ask_drosophila
     *
     * @mbggenerated
     */
    int insertSelective(CibrTaskAskDrosophila record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_ask_drosophila
     *
     * @mbggenerated
     */
    List<CibrTaskAskDrosophila> selectByExample(CibrTaskAskDrosophilaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_ask_drosophila
     *
     * @mbggenerated
     */
    CibrTaskAskDrosophila selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_ask_drosophila
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CibrTaskAskDrosophila record, @Param("example") CibrTaskAskDrosophilaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_ask_drosophila
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CibrTaskAskDrosophila record, @Param("example") CibrTaskAskDrosophilaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_ask_drosophila
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CibrTaskAskDrosophila record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_ask_drosophila
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CibrTaskAskDrosophila record);
}