package com.cibr.animal.demo.dao;

import com.cibr.animal.demo.entity.CibrTaskProcessPrice;
import com.cibr.animal.demo.entity.CibrTaskProcessPriceExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CibrTaskProcessPriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_price
     *
     * @mbggenerated
     */
    int countByExample(CibrTaskProcessPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_price
     *
     * @mbggenerated
     */
    int deleteByExample(CibrTaskProcessPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_price
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_price
     *
     * @mbggenerated
     */
    int insert(CibrTaskProcessPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_price
     *
     * @mbggenerated
     */
    int insertSelective(CibrTaskProcessPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_price
     *
     * @mbggenerated
     */
    List<CibrTaskProcessPrice> selectByExample(CibrTaskProcessPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_price
     *
     * @mbggenerated
     */
    CibrTaskProcessPrice selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_price
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CibrTaskProcessPrice record, @Param("example") CibrTaskProcessPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_price
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CibrTaskProcessPrice record, @Param("example") CibrTaskProcessPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_price
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CibrTaskProcessPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_price
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CibrTaskProcessPrice record);
}