package com.cibr.animal.demo.dao;

import com.cibr.animal.demo.entity.CibrTaskProcess;
import com.cibr.animal.demo.entity.CibrTaskProcessExample;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;
import java.util.Map;

public interface CibrTaskProcessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process
     *
     * @mbggenerated
     */
    int countByExample(CibrTaskProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process
     *
     * @mbggenerated
     */
    int deleteByExample(CibrTaskProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process
     *
     * @mbggenerated
     */
    int insert(CibrTaskProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process
     *
     * @mbggenerated
     */
    int insertSelective(CibrTaskProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process
     *
     * @mbggenerated
     */
    List<CibrTaskProcess> selectByExample(CibrTaskProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process
     *
     * @mbggenerated
     */
    CibrTaskProcess selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CibrTaskProcess record, @Param("example") CibrTaskProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CibrTaskProcess record, @Param("example") CibrTaskProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CibrTaskProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CibrTaskProcess record);

    List<CibrTaskProcess> queryAllProcess(@Param("condition") Map condition);

    List<Map<String,String>> selectAllSampleStatu(@Param("processId") String processId,@Param("userId") String userId);

    List<Map<String,String>> findUnCommitNext(@Param("processId") String processId);

    List<CibrTaskProcess> findAllUsefulTask();

    List<CibrTaskProcess> findbillItems(@Param("firstDay") Date firstDay, @Param("lastDay") Date lastDay);
}