package com.cibr.animal.demo.dao;

import com.cibr.animal.demo.entity.CibrBillDetect;
import com.cibr.animal.demo.entity.CibrBillDetectExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CibrBillDetectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_bill_detect
     *
     * @mbggenerated
     */
    int countByExample(CibrBillDetectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_bill_detect
     *
     * @mbggenerated
     */
    int deleteByExample(CibrBillDetectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_bill_detect
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_bill_detect
     *
     * @mbggenerated
     */
    int insert(CibrBillDetect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_bill_detect
     *
     * @mbggenerated
     */
    int insertSelective(CibrBillDetect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_bill_detect
     *
     * @mbggenerated
     */
    List<CibrBillDetect> selectByExample(CibrBillDetectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_bill_detect
     *
     * @mbggenerated
     */
    CibrBillDetect selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_bill_detect
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CibrBillDetect record, @Param("example") CibrBillDetectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_bill_detect
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CibrBillDetect record, @Param("example") CibrBillDetectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_bill_detect
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CibrBillDetect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_bill_detect
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CibrBillDetect record);
}