package com.cibr.animal.demo.dao;

import com.cibr.animal.demo.entity.CibrTaskProcessDismountdata;
import com.cibr.animal.demo.entity.CibrTaskProcessDismountdataExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface CibrTaskProcessDismountdataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_dismountdata
     *
     * @mbggenerated
     */
    int countByExample(CibrTaskProcessDismountdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_dismountdata
     *
     * @mbggenerated
     */
    int deleteByExample(CibrTaskProcessDismountdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_dismountdata
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_dismountdata
     *
     * @mbggenerated
     */
    int insert(CibrTaskProcessDismountdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_dismountdata
     *
     * @mbggenerated
     */
    int insertSelective(CibrTaskProcessDismountdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_dismountdata
     *
     * @mbggenerated
     */
    List<CibrTaskProcessDismountdata> selectByExample(CibrTaskProcessDismountdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_dismountdata
     *
     * @mbggenerated
     */
    CibrTaskProcessDismountdata selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_dismountdata
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CibrTaskProcessDismountdata record, @Param("example") CibrTaskProcessDismountdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_dismountdata
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CibrTaskProcessDismountdata record, @Param("example") CibrTaskProcessDismountdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_dismountdata
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CibrTaskProcessDismountdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_dismountdata
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CibrTaskProcessDismountdata record);

    int batchInsert(List<CibrTaskProcessDismountdata> list);

    void batchUpdate(List<CibrTaskProcessDismountdata> list);

    List<CibrTaskProcessDismountdata> selectWithCommitNumber(@Param("processId")String processId, @Param("currentStatu")String currentStatu);

    List<Map<String,Object>> selectMake(@Param("list")List<String> list);
}