package com.cibr.animal.demo.dao;

import com.cibr.animal.demo.entity.CibrSysTask;
import com.cibr.animal.demo.entity.CibrSysTaskExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

@Mapper
public interface CibrSysTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_task
     *
     * @mbggenerated
     */
    int countByExample(CibrSysTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_task
     *
     * @mbggenerated
     */
    int deleteByExample(CibrSysTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_task
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_task
     *
     * @mbggenerated
     */
    int insert(CibrSysTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_task
     *
     * @mbggenerated
     */
    int insertSelective(CibrSysTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_task
     *
     * @mbggenerated
     */
    List<CibrSysTask> selectByExample(CibrSysTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_task
     *
     * @mbggenerated
     */
    CibrSysTask selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_task
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CibrSysTask record, @Param("example") CibrSysTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_task
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CibrSysTask record, @Param("example") CibrSysTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CibrSysTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CibrSysTask record);

    List<CibrSysTask> selectByLimit(@Param("condition") Map condition);

    int selectCount(@Param("condition") Map condition);

    int batchUpdate(List<CibrSysTask> list);

    List<CibrSysTask> selectAskTask(@Param("userId") String userId,@Param("flag") String pageLocation);

    List<CibrSysTask> selectPartnerTask(@Param("userId")String userId,@Param("flag") String pageLocation);

    List<CibrSysTask> selectProcessTask(@Param("userId")String userId);

    List<CibrSysTask> selectAllAccountTask(@Param("userId")String userId);

    List<Map<String,String>> findUserTaskCount();

    List<Map<String,String>> findAnimalTaskCount();
}