package com.cibr.animal.demo.dao;

import com.cibr.animal.demo.entity.CibrTaskProcessEmail;
import com.cibr.animal.demo.entity.CibrTaskProcessEmailExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CibrTaskProcessEmailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_email
     *
     * @mbggenerated
     */
    int countByExample(CibrTaskProcessEmailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_email
     *
     * @mbggenerated
     */
    int deleteByExample(CibrTaskProcessEmailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_email
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("processid") String processid, @Param("email") String email);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_email
     *
     * @mbggenerated
     */
    int insert(CibrTaskProcessEmail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_email
     *
     * @mbggenerated
     */
    int insertSelective(CibrTaskProcessEmail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_email
     *
     * @mbggenerated
     */
    List<CibrTaskProcessEmail> selectByExample(CibrTaskProcessEmailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_email
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CibrTaskProcessEmail record, @Param("example") CibrTaskProcessEmailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_email
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CibrTaskProcessEmail record, @Param("example") CibrTaskProcessEmailExample example);

    int batchInsert(List<CibrTaskProcessEmail> list);
}