package com.cibr.animal.demo.dao;

import com.cibr.animal.demo.entity.CibrTaskProcessSamplemake;
import com.cibr.animal.demo.entity.CibrTaskProcessSamplemakeExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CibrTaskProcessSamplemakeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_samplemake
     *
     * @mbggenerated
     */
    int countByExample(CibrTaskProcessSamplemakeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_samplemake
     *
     * @mbggenerated
     */
    int deleteByExample(CibrTaskProcessSamplemakeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_samplemake
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_samplemake
     *
     * @mbggenerated
     */
    int insert(CibrTaskProcessSamplemake record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_samplemake
     *
     * @mbggenerated
     */
    int insertSelective(CibrTaskProcessSamplemake record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_samplemake
     *
     * @mbggenerated
     */
    List<CibrTaskProcessSamplemake> selectByExample(CibrTaskProcessSamplemakeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_samplemake
     *
     * @mbggenerated
     */
    CibrTaskProcessSamplemake selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_samplemake
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CibrTaskProcessSamplemake record, @Param("example") CibrTaskProcessSamplemakeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_samplemake
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CibrTaskProcessSamplemake record, @Param("example") CibrTaskProcessSamplemakeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_samplemake
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CibrTaskProcessSamplemake record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_samplemake
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CibrTaskProcessSamplemake record);
}