package com.cibr.animal.demo.dao;

import com.cibr.animal.demo.entity.CibrTaskProcessSubtask;
import com.cibr.animal.demo.entity.CibrTaskProcessSubtaskExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CibrTaskProcessSubtaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_subtask
     *
     * @mbggenerated
     */
    int countByExample(CibrTaskProcessSubtaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_subtask
     *
     * @mbggenerated
     */
    int deleteByExample(CibrTaskProcessSubtaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_subtask
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_subtask
     *
     * @mbggenerated
     */
    int insert(CibrTaskProcessSubtask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_subtask
     *
     * @mbggenerated
     */
    int insertSelective(CibrTaskProcessSubtask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_subtask
     *
     * @mbggenerated
     */
    List<CibrTaskProcessSubtask> selectByExample(CibrTaskProcessSubtaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_subtask
     *
     * @mbggenerated
     */
    CibrTaskProcessSubtask selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_subtask
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CibrTaskProcessSubtask record, @Param("example") CibrTaskProcessSubtaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_subtask
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CibrTaskProcessSubtask record, @Param("example") CibrTaskProcessSubtaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_subtask
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CibrTaskProcessSubtask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_subtask
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CibrTaskProcessSubtask record);
}