package com.cibr.animal.demo.dao;

import com.cibr.animal.demo.entity.CibrSysVerification;
import com.cibr.animal.demo.entity.CibrSysVerificationExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface CibrSysVerificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_verification
     *
     * @mbggenerated
     */
    int countByExample(CibrSysVerificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_verification
     *
     * @mbggenerated
     */
    int deleteByExample(CibrSysVerificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_verification
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_verification
     *
     * @mbggenerated
     */
    int insert(CibrSysVerification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_verification
     *
     * @mbggenerated
     */
    int insertSelective(CibrSysVerification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_verification
     *
     * @mbggenerated
     */
    List<CibrSysVerification> selectByExample(CibrSysVerificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_verification
     *
     * @mbggenerated
     */
    CibrSysVerification selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_verification
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CibrSysVerification record, @Param("example") CibrSysVerificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_verification
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CibrSysVerification record, @Param("example") CibrSysVerificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_verification
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CibrSysVerification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_verification
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CibrSysVerification record);
}