package com.cibr.animal.demo.entity;

public class CibrSysSampleindex {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_sampleindex.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_sampleindex.curTime
     *
     * @mbggenerated
     */
    private String curtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_sampleindex.currentIndex
     *
     * @mbggenerated
     */
    private Integer currentindex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_sampleindex.name
     *
     * @return the value of cibr_sys_sampleindex.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_sampleindex.name
     *
     * @param name the value for cibr_sys_sampleindex.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_sampleindex.curTime
     *
     * @return the value of cibr_sys_sampleindex.curTime
     *
     * @mbggenerated
     */
    public String getCurtime() {
        return curtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_sampleindex.curTime
     *
     * @param curtime the value for cibr_sys_sampleindex.curTime
     *
     * @mbggenerated
     */
    public void setCurtime(String curtime) {
        this.curtime = curtime == null ? null : curtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_sampleindex.currentIndex
     *
     * @return the value of cibr_sys_sampleindex.currentIndex
     *
     * @mbggenerated
     */
    public Integer getCurrentindex() {
        return currentindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_sampleindex.currentIndex
     *
     * @param currentindex the value for cibr_sys_sampleindex.currentIndex
     *
     * @mbggenerated
     */
    public void setCurrentindex(Integer currentindex) {
        this.currentindex = currentindex;
    }

    public String getSelfNum(){
        String num = String.valueOf(this.currentindex);
        int curLen = 5 - num.length();
        for (int i = 0;i<curLen;i++){
            num = "0" + num;
        }
        return this.name + this.curtime + num;
    }
}