package com.cibr.animal.demo.entity;

public class CibrTaskProcessEmail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_email.processId
     *
     * @mbggenerated
     */
    private String processid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_email.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_email.processId
     *
     * @return the value of cibr_task_process_email.processId
     *
     * @mbggenerated
     */
    public String getProcessid() {
        return processid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_email.processId
     *
     * @param processid the value for cibr_task_process_email.processId
     *
     * @mbggenerated
     */
    public void setProcessid(String processid) {
        this.processid = processid == null ? null : processid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_email.email
     *
     * @return the value of cibr_task_process_email.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_email.email
     *
     * @param email the value for cibr_task_process_email.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }
}