package com.cibr.animal.demo.entity;

import java.util.Date;
import java.util.List;

public class CibrSysUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_user.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_user.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_user.PASSWORD
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_user.EMAIL
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_user.ROLEID
     *
     * @mbggenerated
     */
    private String roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_user.USERDESC
     *
     * @mbggenerated
     */
    private String userdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_user.USERSTATU
     *
     * @mbggenerated
     */
    private String userstatu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_user.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    private List<CibrSysRole> roles;

    public List<CibrSysRole> getRoles() {
        return roles;
    }

    public void setRoles(List<CibrSysRole> roles) {
        this.roles = roles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_user.ID
     *
     * @return the value of cibr_sys_user.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_user.ID
     *
     * @param id the value for cibr_sys_user.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_user.NAME
     *
     * @return the value of cibr_sys_user.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_user.NAME
     *
     * @param name the value for cibr_sys_user.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_user.PASSWORD
     *
     * @return the value of cibr_sys_user.PASSWORD
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_user.PASSWORD
     *
     * @param password the value for cibr_sys_user.PASSWORD
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_user.EMAIL
     *
     * @return the value of cibr_sys_user.EMAIL
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_user.EMAIL
     *
     * @param email the value for cibr_sys_user.EMAIL
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_user.ROLEID
     *
     * @return the value of cibr_sys_user.ROLEID
     *
     * @mbggenerated
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_user.ROLEID
     *
     * @param roleid the value for cibr_sys_user.ROLEID
     *
     * @mbggenerated
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid == null ? null : roleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_user.USERDESC
     *
     * @return the value of cibr_sys_user.USERDESC
     *
     * @mbggenerated
     */
    public String getUserdesc() {
        return userdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_user.USERDESC
     *
     * @param userdesc the value for cibr_sys_user.USERDESC
     *
     * @mbggenerated
     */
    public void setUserdesc(String userdesc) {
        this.userdesc = userdesc == null ? null : userdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_user.USERSTATU
     *
     * @return the value of cibr_sys_user.USERSTATU
     *
     * @mbggenerated
     */
    public String getUserstatu() {
        return userstatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_user.USERSTATU
     *
     * @param userstatu the value for cibr_sys_user.USERSTATU
     *
     * @mbggenerated
     */
    public void setUserstatu(String userstatu) {
        this.userstatu = userstatu == null ? null : userstatu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_user.createtime
     *
     * @return the value of cibr_sys_user.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_user.createtime
     *
     * @param createtime the value for cibr_sys_user.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}