package com.cibr.animal.demo.entity;

import java.util.Date;
import java.util.List;

public class CibrAnimalDrosophila {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_animal_drosophila.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_animal_drosophila.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_animal_drosophila.stock_id
     *
     * @mbggenerated
     */
    private String stockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_animal_drosophila.genotype
     *
     * @mbggenerated
     */
    private String genotype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_animal_drosophila.resource
     *
     * @mbggenerated
     */
    private String resource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_animal_drosophila.parent_id
     *
     * @mbggenerated
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_animal_drosophila.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_animal_drosophila.createUser
     *
     * @mbggenerated
     */
    private String createuser;

    private List<CibrStockDrosophila> stockDrosophilas;

    public List<CibrStockDrosophila> getStockDrosophilas() {
        return stockDrosophilas;
    }

    public void setStockDrosophilas(List<CibrStockDrosophila> stockDrosophilas) {
        this.stockDrosophilas = stockDrosophilas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_animal_drosophila.id
     *
     * @return the value of cibr_animal_drosophila.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_animal_drosophila.id
     *
     * @param id the value for cibr_animal_drosophila.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_animal_drosophila.name
     *
     * @return the value of cibr_animal_drosophila.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_animal_drosophila.name
     *
     * @param name the value for cibr_animal_drosophila.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_animal_drosophila.stock_id
     *
     * @return the value of cibr_animal_drosophila.stock_id
     *
     * @mbggenerated
     */
    public String getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_animal_drosophila.stock_id
     *
     * @param stockId the value for cibr_animal_drosophila.stock_id
     *
     * @mbggenerated
     */
    public void setStockId(String stockId) {
        this.stockId = stockId == null ? null : stockId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_animal_drosophila.genotype
     *
     * @return the value of cibr_animal_drosophila.genotype
     *
     * @mbggenerated
     */
    public String getGenotype() {
        return genotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_animal_drosophila.genotype
     *
     * @param genotype the value for cibr_animal_drosophila.genotype
     *
     * @mbggenerated
     */
    public void setGenotype(String genotype) {
        this.genotype = genotype == null ? null : genotype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_animal_drosophila.resource
     *
     * @return the value of cibr_animal_drosophila.resource
     *
     * @mbggenerated
     */
    public String getResource() {
        return resource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_animal_drosophila.resource
     *
     * @param resource the value for cibr_animal_drosophila.resource
     *
     * @mbggenerated
     */
    public void setResource(String resource) {
        this.resource = resource == null ? null : resource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_animal_drosophila.parent_id
     *
     * @return the value of cibr_animal_drosophila.parent_id
     *
     * @mbggenerated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_animal_drosophila.parent_id
     *
     * @param parentId the value for cibr_animal_drosophila.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_animal_drosophila.createTime
     *
     * @return the value of cibr_animal_drosophila.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_animal_drosophila.createTime
     *
     * @param createtime the value for cibr_animal_drosophila.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_animal_drosophila.createUser
     *
     * @return the value of cibr_animal_drosophila.createUser
     *
     * @mbggenerated
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_animal_drosophila.createUser
     *
     * @param createuser the value for cibr_animal_drosophila.createUser
     *
     * @mbggenerated
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser == null ? null : createuser.trim();
    }
}