package com.cibr.animal.demo.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CibrTaskProcessDiystatuExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cibr_task_process_diystatu
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cibr_task_process_diystatu
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cibr_task_process_diystatu
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_diystatu
     *
     * @mbggenerated
     */
    public CibrTaskProcessDiystatuExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_diystatu
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_diystatu
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_diystatu
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_diystatu
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_diystatu
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_diystatu
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_diystatu
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_diystatu
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_diystatu
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_diystatu
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cibr_task_process_diystatu
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDiynameIsNull() {
            addCriterion("diyName is null");
            return (Criteria) this;
        }

        public Criteria andDiynameIsNotNull() {
            addCriterion("diyName is not null");
            return (Criteria) this;
        }

        public Criteria andDiynameEqualTo(String value) {
            addCriterion("diyName =", value, "diyname");
            return (Criteria) this;
        }

        public Criteria andDiynameNotEqualTo(String value) {
            addCriterion("diyName <>", value, "diyname");
            return (Criteria) this;
        }

        public Criteria andDiynameGreaterThan(String value) {
            addCriterion("diyName >", value, "diyname");
            return (Criteria) this;
        }

        public Criteria andDiynameGreaterThanOrEqualTo(String value) {
            addCriterion("diyName >=", value, "diyname");
            return (Criteria) this;
        }

        public Criteria andDiynameLessThan(String value) {
            addCriterion("diyName <", value, "diyname");
            return (Criteria) this;
        }

        public Criteria andDiynameLessThanOrEqualTo(String value) {
            addCriterion("diyName <=", value, "diyname");
            return (Criteria) this;
        }

        public Criteria andDiynameLike(String value) {
            addCriterion("diyName like", value, "diyname");
            return (Criteria) this;
        }

        public Criteria andDiynameNotLike(String value) {
            addCriterion("diyName not like", value, "diyname");
            return (Criteria) this;
        }

        public Criteria andDiynameIn(List<String> values) {
            addCriterion("diyName in", values, "diyname");
            return (Criteria) this;
        }

        public Criteria andDiynameNotIn(List<String> values) {
            addCriterion("diyName not in", values, "diyname");
            return (Criteria) this;
        }

        public Criteria andDiynameBetween(String value1, String value2) {
            addCriterion("diyName between", value1, value2, "diyname");
            return (Criteria) this;
        }

        public Criteria andDiynameNotBetween(String value1, String value2) {
            addCriterion("diyName not between", value1, value2, "diyname");
            return (Criteria) this;
        }

        public Criteria andDiystatuIsNull() {
            addCriterion("diystatu is null");
            return (Criteria) this;
        }

        public Criteria andDiystatuIsNotNull() {
            addCriterion("diystatu is not null");
            return (Criteria) this;
        }

        public Criteria andDiystatuEqualTo(String value) {
            addCriterion("diystatu =", value, "diystatu");
            return (Criteria) this;
        }

        public Criteria andDiystatuNotEqualTo(String value) {
            addCriterion("diystatu <>", value, "diystatu");
            return (Criteria) this;
        }

        public Criteria andDiystatuGreaterThan(String value) {
            addCriterion("diystatu >", value, "diystatu");
            return (Criteria) this;
        }

        public Criteria andDiystatuGreaterThanOrEqualTo(String value) {
            addCriterion("diystatu >=", value, "diystatu");
            return (Criteria) this;
        }

        public Criteria andDiystatuLessThan(String value) {
            addCriterion("diystatu <", value, "diystatu");
            return (Criteria) this;
        }

        public Criteria andDiystatuLessThanOrEqualTo(String value) {
            addCriterion("diystatu <=", value, "diystatu");
            return (Criteria) this;
        }

        public Criteria andDiystatuLike(String value) {
            addCriterion("diystatu like", value, "diystatu");
            return (Criteria) this;
        }

        public Criteria andDiystatuNotLike(String value) {
            addCriterion("diystatu not like", value, "diystatu");
            return (Criteria) this;
        }

        public Criteria andDiystatuIn(List<String> values) {
            addCriterion("diystatu in", values, "diystatu");
            return (Criteria) this;
        }

        public Criteria andDiystatuNotIn(List<String> values) {
            addCriterion("diystatu not in", values, "diystatu");
            return (Criteria) this;
        }

        public Criteria andDiystatuBetween(String value1, String value2) {
            addCriterion("diystatu between", value1, value2, "diystatu");
            return (Criteria) this;
        }

        public Criteria andDiystatuNotBetween(String value1, String value2) {
            addCriterion("diystatu not between", value1, value2, "diystatu");
            return (Criteria) this;
        }

        public Criteria andConnectsampleIsNull() {
            addCriterion("connectSample is null");
            return (Criteria) this;
        }

        public Criteria andConnectsampleIsNotNull() {
            addCriterion("connectSample is not null");
            return (Criteria) this;
        }

        public Criteria andConnectsampleEqualTo(String value) {
            addCriterion("connectSample =", value, "connectsample");
            return (Criteria) this;
        }

        public Criteria andConnectsampleNotEqualTo(String value) {
            addCriterion("connectSample <>", value, "connectsample");
            return (Criteria) this;
        }

        public Criteria andConnectsampleGreaterThan(String value) {
            addCriterion("connectSample >", value, "connectsample");
            return (Criteria) this;
        }

        public Criteria andConnectsampleGreaterThanOrEqualTo(String value) {
            addCriterion("connectSample >=", value, "connectsample");
            return (Criteria) this;
        }

        public Criteria andConnectsampleLessThan(String value) {
            addCriterion("connectSample <", value, "connectsample");
            return (Criteria) this;
        }

        public Criteria andConnectsampleLessThanOrEqualTo(String value) {
            addCriterion("connectSample <=", value, "connectsample");
            return (Criteria) this;
        }

        public Criteria andConnectsampleLike(String value) {
            addCriterion("connectSample like", value, "connectsample");
            return (Criteria) this;
        }

        public Criteria andConnectsampleNotLike(String value) {
            addCriterion("connectSample not like", value, "connectsample");
            return (Criteria) this;
        }

        public Criteria andConnectsampleIn(List<String> values) {
            addCriterion("connectSample in", values, "connectsample");
            return (Criteria) this;
        }

        public Criteria andConnectsampleNotIn(List<String> values) {
            addCriterion("connectSample not in", values, "connectsample");
            return (Criteria) this;
        }

        public Criteria andConnectsampleBetween(String value1, String value2) {
            addCriterion("connectSample between", value1, value2, "connectsample");
            return (Criteria) this;
        }

        public Criteria andConnectsampleNotBetween(String value1, String value2) {
            addCriterion("connectSample not between", value1, value2, "connectsample");
            return (Criteria) this;
        }

        public Criteria andCurstatuIsNull() {
            addCriterion("curstatu is null");
            return (Criteria) this;
        }

        public Criteria andCurstatuIsNotNull() {
            addCriterion("curstatu is not null");
            return (Criteria) this;
        }

        public Criteria andCurstatuEqualTo(String value) {
            addCriterion("curstatu =", value, "curstatu");
            return (Criteria) this;
        }

        public Criteria andCurstatuNotEqualTo(String value) {
            addCriterion("curstatu <>", value, "curstatu");
            return (Criteria) this;
        }

        public Criteria andCurstatuGreaterThan(String value) {
            addCriterion("curstatu >", value, "curstatu");
            return (Criteria) this;
        }

        public Criteria andCurstatuGreaterThanOrEqualTo(String value) {
            addCriterion("curstatu >=", value, "curstatu");
            return (Criteria) this;
        }

        public Criteria andCurstatuLessThan(String value) {
            addCriterion("curstatu <", value, "curstatu");
            return (Criteria) this;
        }

        public Criteria andCurstatuLessThanOrEqualTo(String value) {
            addCriterion("curstatu <=", value, "curstatu");
            return (Criteria) this;
        }

        public Criteria andCurstatuLike(String value) {
            addCriterion("curstatu like", value, "curstatu");
            return (Criteria) this;
        }

        public Criteria andCurstatuNotLike(String value) {
            addCriterion("curstatu not like", value, "curstatu");
            return (Criteria) this;
        }

        public Criteria andCurstatuIn(List<String> values) {
            addCriterion("curstatu in", values, "curstatu");
            return (Criteria) this;
        }

        public Criteria andCurstatuNotIn(List<String> values) {
            addCriterion("curstatu not in", values, "curstatu");
            return (Criteria) this;
        }

        public Criteria andCurstatuBetween(String value1, String value2) {
            addCriterion("curstatu between", value1, value2, "curstatu");
            return (Criteria) this;
        }

        public Criteria andCurstatuNotBetween(String value1, String value2) {
            addCriterion("curstatu not between", value1, value2, "curstatu");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNull() {
            addCriterion("creater is null");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNotNull() {
            addCriterion("creater is not null");
            return (Criteria) this;
        }

        public Criteria andCreaterEqualTo(String value) {
            addCriterion("creater =", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotEqualTo(String value) {
            addCriterion("creater <>", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThan(String value) {
            addCriterion("creater >", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThanOrEqualTo(String value) {
            addCriterion("creater >=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThan(String value) {
            addCriterion("creater <", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThanOrEqualTo(String value) {
            addCriterion("creater <=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLike(String value) {
            addCriterion("creater like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotLike(String value) {
            addCriterion("creater not like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterIn(List<String> values) {
            addCriterion("creater in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotIn(List<String> values) {
            addCriterion("creater not in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterBetween(String value1, String value2) {
            addCriterion("creater between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotBetween(String value1, String value2) {
            addCriterion("creater not between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andProcessidIsNull() {
            addCriterion("processId is null");
            return (Criteria) this;
        }

        public Criteria andProcessidIsNotNull() {
            addCriterion("processId is not null");
            return (Criteria) this;
        }

        public Criteria andProcessidEqualTo(String value) {
            addCriterion("processId =", value, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidNotEqualTo(String value) {
            addCriterion("processId <>", value, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidGreaterThan(String value) {
            addCriterion("processId >", value, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidGreaterThanOrEqualTo(String value) {
            addCriterion("processId >=", value, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidLessThan(String value) {
            addCriterion("processId <", value, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidLessThanOrEqualTo(String value) {
            addCriterion("processId <=", value, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidLike(String value) {
            addCriterion("processId like", value, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidNotLike(String value) {
            addCriterion("processId not like", value, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidIn(List<String> values) {
            addCriterion("processId in", values, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidNotIn(List<String> values) {
            addCriterion("processId not in", values, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidBetween(String value1, String value2) {
            addCriterion("processId between", value1, value2, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidNotBetween(String value1, String value2) {
            addCriterion("processId not between", value1, value2, "processid");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterion("updateTime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterion("updateTime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterion("updateTime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updateTime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterion("updateTime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("updateTime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterion("updateTime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterion("updateTime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("updateTime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("updateTime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNull() {
            addCriterion("updater is null");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNotNull() {
            addCriterion("updater is not null");
            return (Criteria) this;
        }

        public Criteria andUpdaterEqualTo(String value) {
            addCriterion("updater =", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotEqualTo(String value) {
            addCriterion("updater <>", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThan(String value) {
            addCriterion("updater >", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThanOrEqualTo(String value) {
            addCriterion("updater >=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThan(String value) {
            addCriterion("updater <", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThanOrEqualTo(String value) {
            addCriterion("updater <=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLike(String value) {
            addCriterion("updater like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotLike(String value) {
            addCriterion("updater not like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterIn(List<String> values) {
            addCriterion("updater in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotIn(List<String> values) {
            addCriterion("updater not in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterBetween(String value1, String value2) {
            addCriterion("updater between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotBetween(String value1, String value2) {
            addCriterion("updater not between", value1, value2, "updater");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cibr_task_process_diystatu
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cibr_task_process_diystatu
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}