package com.cibr.animal.demo.entity;

import java.util.Date;
import java.util.List;

public class CibrTaskProcess {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process.taskid
     *
     * @mbggenerated
     */
    private String taskid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process.creater
     *
     * @mbggenerated
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process.taskstatu
     *
     * @mbggenerated
     */
    private String taskstatu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process.projectName
     *
     * @mbggenerated
     */
    private String projectname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process.dataType
     *
     * @mbggenerated
     */
    private String datatype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process.principal
     *
     * @mbggenerated
     */
    private String principal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process.sampleType
     *
     * @mbggenerated
     */
    private String sampletype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process.sampleInput
     *
     * @mbggenerated
     */
    private String sampleinput;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process.inputTime
     *
     * @mbggenerated
     */
    private Date inputtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process.samplePreparation
     *
     * @mbggenerated
     */
    private String samplepreparation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process.spupdateTime
     *
     * @mbggenerated
     */
    private Date spupdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process.libraryPreparation
     *
     * @mbggenerated
     */
    private String librarypreparation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process.lpupdateTime
     *
     * @mbggenerated
     */
    private Date lpupdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process.dismountData
     *
     * @mbggenerated
     */
    private String dismountdata;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process.ddupdateTime
     *
     * @mbggenerated
     */
    private Date ddupdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process.bioinformaticsAnalysis
     *
     * @mbggenerated
     */
    private String bioinformaticsanalysis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process.baupdateTime
     *
     * @mbggenerated
     */
    private Date baupdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process.projectDesc
     *
     * @mbggenerated
     */
    private String projectdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process.isOnlyBio
     *
     * @mbggenerated
     */
    private Boolean isonlybio;

    private List<String> emails;

    public List<String> getEmails() {
        return emails;
    }

    public void setEmails(List<String> emails) {
        this.emails = emails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process.id
     *
     * @return the value of cibr_task_process.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process.id
     *
     * @param id the value for cibr_task_process.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process.taskid
     *
     * @return the value of cibr_task_process.taskid
     *
     * @mbggenerated
     */
    public String getTaskid() {
        return taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process.taskid
     *
     * @param taskid the value for cibr_task_process.taskid
     *
     * @mbggenerated
     */
    public void setTaskid(String taskid) {
        this.taskid = taskid == null ? null : taskid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process.creater
     *
     * @return the value of cibr_task_process.creater
     *
     * @mbggenerated
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process.creater
     *
     * @param creater the value for cibr_task_process.creater
     *
     * @mbggenerated
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process.createTime
     *
     * @return the value of cibr_task_process.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process.createTime
     *
     * @param createtime the value for cibr_task_process.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process.taskstatu
     *
     * @return the value of cibr_task_process.taskstatu
     *
     * @mbggenerated
     */
    public String getTaskstatu() {
        return taskstatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process.taskstatu
     *
     * @param taskstatu the value for cibr_task_process.taskstatu
     *
     * @mbggenerated
     */
    public void setTaskstatu(String taskstatu) {
        this.taskstatu = taskstatu == null ? null : taskstatu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process.projectName
     *
     * @return the value of cibr_task_process.projectName
     *
     * @mbggenerated
     */
    public String getProjectname() {
        return projectname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process.projectName
     *
     * @param projectname the value for cibr_task_process.projectName
     *
     * @mbggenerated
     */
    public void setProjectname(String projectname) {
        this.projectname = projectname == null ? null : projectname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process.dataType
     *
     * @return the value of cibr_task_process.dataType
     *
     * @mbggenerated
     */
    public String getDatatype() {
        return datatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process.dataType
     *
     * @param datatype the value for cibr_task_process.dataType
     *
     * @mbggenerated
     */
    public void setDatatype(String datatype) {
        this.datatype = datatype == null ? null : datatype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process.principal
     *
     * @return the value of cibr_task_process.principal
     *
     * @mbggenerated
     */
    public String getPrincipal() {
        return principal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process.principal
     *
     * @param principal the value for cibr_task_process.principal
     *
     * @mbggenerated
     */
    public void setPrincipal(String principal) {
        this.principal = principal == null ? null : principal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process.sampleType
     *
     * @return the value of cibr_task_process.sampleType
     *
     * @mbggenerated
     */
    public String getSampletype() {
        return sampletype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process.sampleType
     *
     * @param sampletype the value for cibr_task_process.sampleType
     *
     * @mbggenerated
     */
    public void setSampletype(String sampletype) {
        this.sampletype = sampletype == null ? null : sampletype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process.sampleInput
     *
     * @return the value of cibr_task_process.sampleInput
     *
     * @mbggenerated
     */
    public String getSampleinput() {
        return sampleinput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process.sampleInput
     *
     * @param sampleinput the value for cibr_task_process.sampleInput
     *
     * @mbggenerated
     */
    public void setSampleinput(String sampleinput) {
        this.sampleinput = sampleinput == null ? null : sampleinput.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process.inputTime
     *
     * @return the value of cibr_task_process.inputTime
     *
     * @mbggenerated
     */
    public Date getInputtime() {
        return inputtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process.inputTime
     *
     * @param inputtime the value for cibr_task_process.inputTime
     *
     * @mbggenerated
     */
    public void setInputtime(Date inputtime) {
        this.inputtime = inputtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process.samplePreparation
     *
     * @return the value of cibr_task_process.samplePreparation
     *
     * @mbggenerated
     */
    public String getSamplepreparation() {
        return samplepreparation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process.samplePreparation
     *
     * @param samplepreparation the value for cibr_task_process.samplePreparation
     *
     * @mbggenerated
     */
    public void setSamplepreparation(String samplepreparation) {
        this.samplepreparation = samplepreparation == null ? null : samplepreparation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process.spupdateTime
     *
     * @return the value of cibr_task_process.spupdateTime
     *
     * @mbggenerated
     */
    public Date getSpupdatetime() {
        return spupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process.spupdateTime
     *
     * @param spupdatetime the value for cibr_task_process.spupdateTime
     *
     * @mbggenerated
     */
    public void setSpupdatetime(Date spupdatetime) {
        this.spupdatetime = spupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process.libraryPreparation
     *
     * @return the value of cibr_task_process.libraryPreparation
     *
     * @mbggenerated
     */
    public String getLibrarypreparation() {
        return librarypreparation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process.libraryPreparation
     *
     * @param librarypreparation the value for cibr_task_process.libraryPreparation
     *
     * @mbggenerated
     */
    public void setLibrarypreparation(String librarypreparation) {
        this.librarypreparation = librarypreparation == null ? null : librarypreparation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process.lpupdateTime
     *
     * @return the value of cibr_task_process.lpupdateTime
     *
     * @mbggenerated
     */
    public Date getLpupdatetime() {
        return lpupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process.lpupdateTime
     *
     * @param lpupdatetime the value for cibr_task_process.lpupdateTime
     *
     * @mbggenerated
     */
    public void setLpupdatetime(Date lpupdatetime) {
        this.lpupdatetime = lpupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process.dismountData
     *
     * @return the value of cibr_task_process.dismountData
     *
     * @mbggenerated
     */
    public String getDismountdata() {
        return dismountdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process.dismountData
     *
     * @param dismountdata the value for cibr_task_process.dismountData
     *
     * @mbggenerated
     */
    public void setDismountdata(String dismountdata) {
        this.dismountdata = dismountdata == null ? null : dismountdata.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process.ddupdateTime
     *
     * @return the value of cibr_task_process.ddupdateTime
     *
     * @mbggenerated
     */
    public Date getDdupdatetime() {
        return ddupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process.ddupdateTime
     *
     * @param ddupdatetime the value for cibr_task_process.ddupdateTime
     *
     * @mbggenerated
     */
    public void setDdupdatetime(Date ddupdatetime) {
        this.ddupdatetime = ddupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process.bioinformaticsAnalysis
     *
     * @return the value of cibr_task_process.bioinformaticsAnalysis
     *
     * @mbggenerated
     */
    public String getBioinformaticsanalysis() {
        return bioinformaticsanalysis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process.bioinformaticsAnalysis
     *
     * @param bioinformaticsanalysis the value for cibr_task_process.bioinformaticsAnalysis
     *
     * @mbggenerated
     */
    public void setBioinformaticsanalysis(String bioinformaticsanalysis) {
        this.bioinformaticsanalysis = bioinformaticsanalysis == null ? null : bioinformaticsanalysis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process.baupdateTime
     *
     * @return the value of cibr_task_process.baupdateTime
     *
     * @mbggenerated
     */
    public Date getBaupdatetime() {
        return baupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process.baupdateTime
     *
     * @param baupdatetime the value for cibr_task_process.baupdateTime
     *
     * @mbggenerated
     */
    public void setBaupdatetime(Date baupdatetime) {
        this.baupdatetime = baupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process.remarks
     *
     * @return the value of cibr_task_process.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process.remarks
     *
     * @param remarks the value for cibr_task_process.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process.projectDesc
     *
     * @return the value of cibr_task_process.projectDesc
     *
     * @mbggenerated
     */
    public String getProjectdesc() {
        return projectdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process.projectDesc
     *
     * @param projectdesc the value for cibr_task_process.projectDesc
     *
     * @mbggenerated
     */
    public void setProjectdesc(String projectdesc) {
        this.projectdesc = projectdesc == null ? null : projectdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process.isOnlyBio
     *
     * @return the value of cibr_task_process.isOnlyBio
     *
     * @mbggenerated
     */
    public Boolean getIsonlybio() {
        return isonlybio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process.isOnlyBio
     *
     * @param isonlybio the value for cibr_task_process.isOnlyBio
     *
     * @mbggenerated
     */
    public void setIsonlybio(Boolean isonlybio) {
        this.isonlybio = isonlybio;
    }
}