package com.cibr.animal.demo.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CibrStockDrosophilaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cibr_stock_drosophila
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cibr_stock_drosophila
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cibr_stock_drosophila
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_stock_drosophila
     *
     * @mbggenerated
     */
    public CibrStockDrosophilaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_stock_drosophila
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_stock_drosophila
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_stock_drosophila
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_stock_drosophila
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_stock_drosophila
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_stock_drosophila
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_stock_drosophila
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_stock_drosophila
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_stock_drosophila
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_stock_drosophila
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cibr_stock_drosophila
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDrosophilaIdIsNull() {
            addCriterion("drosophila_id is null");
            return (Criteria) this;
        }

        public Criteria andDrosophilaIdIsNotNull() {
            addCriterion("drosophila_id is not null");
            return (Criteria) this;
        }

        public Criteria andDrosophilaIdEqualTo(String value) {
            addCriterion("drosophila_id =", value, "drosophilaId");
            return (Criteria) this;
        }

        public Criteria andDrosophilaIdNotEqualTo(String value) {
            addCriterion("drosophila_id <>", value, "drosophilaId");
            return (Criteria) this;
        }

        public Criteria andDrosophilaIdGreaterThan(String value) {
            addCriterion("drosophila_id >", value, "drosophilaId");
            return (Criteria) this;
        }

        public Criteria andDrosophilaIdGreaterThanOrEqualTo(String value) {
            addCriterion("drosophila_id >=", value, "drosophilaId");
            return (Criteria) this;
        }

        public Criteria andDrosophilaIdLessThan(String value) {
            addCriterion("drosophila_id <", value, "drosophilaId");
            return (Criteria) this;
        }

        public Criteria andDrosophilaIdLessThanOrEqualTo(String value) {
            addCriterion("drosophila_id <=", value, "drosophilaId");
            return (Criteria) this;
        }

        public Criteria andDrosophilaIdLike(String value) {
            addCriterion("drosophila_id like", value, "drosophilaId");
            return (Criteria) this;
        }

        public Criteria andDrosophilaIdNotLike(String value) {
            addCriterion("drosophila_id not like", value, "drosophilaId");
            return (Criteria) this;
        }

        public Criteria andDrosophilaIdIn(List<String> values) {
            addCriterion("drosophila_id in", values, "drosophilaId");
            return (Criteria) this;
        }

        public Criteria andDrosophilaIdNotIn(List<String> values) {
            addCriterion("drosophila_id not in", values, "drosophilaId");
            return (Criteria) this;
        }

        public Criteria andDrosophilaIdBetween(String value1, String value2) {
            addCriterion("drosophila_id between", value1, value2, "drosophilaId");
            return (Criteria) this;
        }

        public Criteria andDrosophilaIdNotBetween(String value1, String value2) {
            addCriterion("drosophila_id not between", value1, value2, "drosophilaId");
            return (Criteria) this;
        }

        public Criteria andContanertypeIsNull() {
            addCriterion("contanerType is null");
            return (Criteria) this;
        }

        public Criteria andContanertypeIsNotNull() {
            addCriterion("contanerType is not null");
            return (Criteria) this;
        }

        public Criteria andContanertypeEqualTo(String value) {
            addCriterion("contanerType =", value, "contanertype");
            return (Criteria) this;
        }

        public Criteria andContanertypeNotEqualTo(String value) {
            addCriterion("contanerType <>", value, "contanertype");
            return (Criteria) this;
        }

        public Criteria andContanertypeGreaterThan(String value) {
            addCriterion("contanerType >", value, "contanertype");
            return (Criteria) this;
        }

        public Criteria andContanertypeGreaterThanOrEqualTo(String value) {
            addCriterion("contanerType >=", value, "contanertype");
            return (Criteria) this;
        }

        public Criteria andContanertypeLessThan(String value) {
            addCriterion("contanerType <", value, "contanertype");
            return (Criteria) this;
        }

        public Criteria andContanertypeLessThanOrEqualTo(String value) {
            addCriterion("contanerType <=", value, "contanertype");
            return (Criteria) this;
        }

        public Criteria andContanertypeLike(String value) {
            addCriterion("contanerType like", value, "contanertype");
            return (Criteria) this;
        }

        public Criteria andContanertypeNotLike(String value) {
            addCriterion("contanerType not like", value, "contanertype");
            return (Criteria) this;
        }

        public Criteria andContanertypeIn(List<String> values) {
            addCriterion("contanerType in", values, "contanertype");
            return (Criteria) this;
        }

        public Criteria andContanertypeNotIn(List<String> values) {
            addCriterion("contanerType not in", values, "contanertype");
            return (Criteria) this;
        }

        public Criteria andContanertypeBetween(String value1, String value2) {
            addCriterion("contanerType between", value1, value2, "contanertype");
            return (Criteria) this;
        }

        public Criteria andContanertypeNotBetween(String value1, String value2) {
            addCriterion("contanerType not between", value1, value2, "contanertype");
            return (Criteria) this;
        }

        public Criteria andContanernmuberIsNull() {
            addCriterion("contanerNmuber is null");
            return (Criteria) this;
        }

        public Criteria andContanernmuberIsNotNull() {
            addCriterion("contanerNmuber is not null");
            return (Criteria) this;
        }

        public Criteria andContanernmuberEqualTo(Integer value) {
            addCriterion("contanerNmuber =", value, "contanernmuber");
            return (Criteria) this;
        }

        public Criteria andContanernmuberNotEqualTo(Integer value) {
            addCriterion("contanerNmuber <>", value, "contanernmuber");
            return (Criteria) this;
        }

        public Criteria andContanernmuberGreaterThan(Integer value) {
            addCriterion("contanerNmuber >", value, "contanernmuber");
            return (Criteria) this;
        }

        public Criteria andContanernmuberGreaterThanOrEqualTo(Integer value) {
            addCriterion("contanerNmuber >=", value, "contanernmuber");
            return (Criteria) this;
        }

        public Criteria andContanernmuberLessThan(Integer value) {
            addCriterion("contanerNmuber <", value, "contanernmuber");
            return (Criteria) this;
        }

        public Criteria andContanernmuberLessThanOrEqualTo(Integer value) {
            addCriterion("contanerNmuber <=", value, "contanernmuber");
            return (Criteria) this;
        }

        public Criteria andContanernmuberIn(List<Integer> values) {
            addCriterion("contanerNmuber in", values, "contanernmuber");
            return (Criteria) this;
        }

        public Criteria andContanernmuberNotIn(List<Integer> values) {
            addCriterion("contanerNmuber not in", values, "contanernmuber");
            return (Criteria) this;
        }

        public Criteria andContanernmuberBetween(Integer value1, Integer value2) {
            addCriterion("contanerNmuber between", value1, value2, "contanernmuber");
            return (Criteria) this;
        }

        public Criteria andContanernmuberNotBetween(Integer value1, Integer value2) {
            addCriterion("contanerNmuber not between", value1, value2, "contanernmuber");
            return (Criteria) this;
        }

        public Criteria andUsagetypeIsNull() {
            addCriterion("usageType is null");
            return (Criteria) this;
        }

        public Criteria andUsagetypeIsNotNull() {
            addCriterion("usageType is not null");
            return (Criteria) this;
        }

        public Criteria andUsagetypeEqualTo(String value) {
            addCriterion("usageType =", value, "usagetype");
            return (Criteria) this;
        }

        public Criteria andUsagetypeNotEqualTo(String value) {
            addCriterion("usageType <>", value, "usagetype");
            return (Criteria) this;
        }

        public Criteria andUsagetypeGreaterThan(String value) {
            addCriterion("usageType >", value, "usagetype");
            return (Criteria) this;
        }

        public Criteria andUsagetypeGreaterThanOrEqualTo(String value) {
            addCriterion("usageType >=", value, "usagetype");
            return (Criteria) this;
        }

        public Criteria andUsagetypeLessThan(String value) {
            addCriterion("usageType <", value, "usagetype");
            return (Criteria) this;
        }

        public Criteria andUsagetypeLessThanOrEqualTo(String value) {
            addCriterion("usageType <=", value, "usagetype");
            return (Criteria) this;
        }

        public Criteria andUsagetypeLike(String value) {
            addCriterion("usageType like", value, "usagetype");
            return (Criteria) this;
        }

        public Criteria andUsagetypeNotLike(String value) {
            addCriterion("usageType not like", value, "usagetype");
            return (Criteria) this;
        }

        public Criteria andUsagetypeIn(List<String> values) {
            addCriterion("usageType in", values, "usagetype");
            return (Criteria) this;
        }

        public Criteria andUsagetypeNotIn(List<String> values) {
            addCriterion("usageType not in", values, "usagetype");
            return (Criteria) this;
        }

        public Criteria andUsagetypeBetween(String value1, String value2) {
            addCriterion("usageType between", value1, value2, "usagetype");
            return (Criteria) this;
        }

        public Criteria andUsagetypeNotBetween(String value1, String value2) {
            addCriterion("usageType not between", value1, value2, "usagetype");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNull() {
            addCriterion("birthday is null");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNotNull() {
            addCriterion("birthday is not null");
            return (Criteria) this;
        }

        public Criteria andBirthdayEqualTo(Date value) {
            addCriterion("birthday =", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotEqualTo(Date value) {
            addCriterion("birthday <>", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThan(Date value) {
            addCriterion("birthday >", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThanOrEqualTo(Date value) {
            addCriterion("birthday >=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThan(Date value) {
            addCriterion("birthday <", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThanOrEqualTo(Date value) {
            addCriterion("birthday <=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayIn(List<Date> values) {
            addCriterion("birthday in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotIn(List<Date> values) {
            addCriterion("birthday not in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayBetween(Date value1, Date value2) {
            addCriterion("birthday between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotBetween(Date value1, Date value2) {
            addCriterion("birthday not between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andCreateuserIsNull() {
            addCriterion("createUser is null");
            return (Criteria) this;
        }

        public Criteria andCreateuserIsNotNull() {
            addCriterion("createUser is not null");
            return (Criteria) this;
        }

        public Criteria andCreateuserEqualTo(String value) {
            addCriterion("createUser =", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotEqualTo(String value) {
            addCriterion("createUser <>", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserGreaterThan(String value) {
            addCriterion("createUser >", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserGreaterThanOrEqualTo(String value) {
            addCriterion("createUser >=", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLessThan(String value) {
            addCriterion("createUser <", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLessThanOrEqualTo(String value) {
            addCriterion("createUser <=", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLike(String value) {
            addCriterion("createUser like", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotLike(String value) {
            addCriterion("createUser not like", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserIn(List<String> values) {
            addCriterion("createUser in", values, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotIn(List<String> values) {
            addCriterion("createUser not in", values, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserBetween(String value1, String value2) {
            addCriterion("createUser between", value1, value2, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotBetween(String value1, String value2) {
            addCriterion("createUser not between", value1, value2, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andLocationIsNull() {
            addCriterion("location is null");
            return (Criteria) this;
        }

        public Criteria andLocationIsNotNull() {
            addCriterion("location is not null");
            return (Criteria) this;
        }

        public Criteria andLocationEqualTo(String value) {
            addCriterion("location =", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotEqualTo(String value) {
            addCriterion("location <>", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationGreaterThan(String value) {
            addCriterion("location >", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationGreaterThanOrEqualTo(String value) {
            addCriterion("location >=", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLessThan(String value) {
            addCriterion("location <", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLessThanOrEqualTo(String value) {
            addCriterion("location <=", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLike(String value) {
            addCriterion("location like", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotLike(String value) {
            addCriterion("location not like", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationIn(List<String> values) {
            addCriterion("location in", values, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotIn(List<String> values) {
            addCriterion("location not in", values, "location");
            return (Criteria) this;
        }

        public Criteria andLocationBetween(String value1, String value2) {
            addCriterion("location between", value1, value2, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotBetween(String value1, String value2) {
            addCriterion("location not between", value1, value2, "location");
            return (Criteria) this;
        }

        public Criteria andRawnumberIsNull() {
            addCriterion("rawNumber is null");
            return (Criteria) this;
        }

        public Criteria andRawnumberIsNotNull() {
            addCriterion("rawNumber is not null");
            return (Criteria) this;
        }

        public Criteria andRawnumberEqualTo(Integer value) {
            addCriterion("rawNumber =", value, "rawnumber");
            return (Criteria) this;
        }

        public Criteria andRawnumberNotEqualTo(Integer value) {
            addCriterion("rawNumber <>", value, "rawnumber");
            return (Criteria) this;
        }

        public Criteria andRawnumberGreaterThan(Integer value) {
            addCriterion("rawNumber >", value, "rawnumber");
            return (Criteria) this;
        }

        public Criteria andRawnumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("rawNumber >=", value, "rawnumber");
            return (Criteria) this;
        }

        public Criteria andRawnumberLessThan(Integer value) {
            addCriterion("rawNumber <", value, "rawnumber");
            return (Criteria) this;
        }

        public Criteria andRawnumberLessThanOrEqualTo(Integer value) {
            addCriterion("rawNumber <=", value, "rawnumber");
            return (Criteria) this;
        }

        public Criteria andRawnumberIn(List<Integer> values) {
            addCriterion("rawNumber in", values, "rawnumber");
            return (Criteria) this;
        }

        public Criteria andRawnumberNotIn(List<Integer> values) {
            addCriterion("rawNumber not in", values, "rawnumber");
            return (Criteria) this;
        }

        public Criteria andRawnumberBetween(Integer value1, Integer value2) {
            addCriterion("rawNumber between", value1, value2, "rawnumber");
            return (Criteria) this;
        }

        public Criteria andRawnumberNotBetween(Integer value1, Integer value2) {
            addCriterion("rawNumber not between", value1, value2, "rawnumber");
            return (Criteria) this;
        }

        public Criteria andRawtypeIsNull() {
            addCriterion("rawType is null");
            return (Criteria) this;
        }

        public Criteria andRawtypeIsNotNull() {
            addCriterion("rawType is not null");
            return (Criteria) this;
        }

        public Criteria andRawtypeEqualTo(String value) {
            addCriterion("rawType =", value, "rawtype");
            return (Criteria) this;
        }

        public Criteria andRawtypeNotEqualTo(String value) {
            addCriterion("rawType <>", value, "rawtype");
            return (Criteria) this;
        }

        public Criteria andRawtypeGreaterThan(String value) {
            addCriterion("rawType >", value, "rawtype");
            return (Criteria) this;
        }

        public Criteria andRawtypeGreaterThanOrEqualTo(String value) {
            addCriterion("rawType >=", value, "rawtype");
            return (Criteria) this;
        }

        public Criteria andRawtypeLessThan(String value) {
            addCriterion("rawType <", value, "rawtype");
            return (Criteria) this;
        }

        public Criteria andRawtypeLessThanOrEqualTo(String value) {
            addCriterion("rawType <=", value, "rawtype");
            return (Criteria) this;
        }

        public Criteria andRawtypeLike(String value) {
            addCriterion("rawType like", value, "rawtype");
            return (Criteria) this;
        }

        public Criteria andRawtypeNotLike(String value) {
            addCriterion("rawType not like", value, "rawtype");
            return (Criteria) this;
        }

        public Criteria andRawtypeIn(List<String> values) {
            addCriterion("rawType in", values, "rawtype");
            return (Criteria) this;
        }

        public Criteria andRawtypeNotIn(List<String> values) {
            addCriterion("rawType not in", values, "rawtype");
            return (Criteria) this;
        }

        public Criteria andRawtypeBetween(String value1, String value2) {
            addCriterion("rawType between", value1, value2, "rawtype");
            return (Criteria) this;
        }

        public Criteria andRawtypeNotBetween(String value1, String value2) {
            addCriterion("rawType not between", value1, value2, "rawtype");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterion("updateTime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterion("updateTime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterion("updateTime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updateTime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterion("updateTime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("updateTime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterion("updateTime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterion("updateTime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("updateTime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("updateTime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateuserIsNull() {
            addCriterion("updateUser is null");
            return (Criteria) this;
        }

        public Criteria andUpdateuserIsNotNull() {
            addCriterion("updateUser is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateuserEqualTo(String value) {
            addCriterion("updateUser =", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserNotEqualTo(String value) {
            addCriterion("updateUser <>", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserGreaterThan(String value) {
            addCriterion("updateUser >", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserGreaterThanOrEqualTo(String value) {
            addCriterion("updateUser >=", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserLessThan(String value) {
            addCriterion("updateUser <", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserLessThanOrEqualTo(String value) {
            addCriterion("updateUser <=", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserLike(String value) {
            addCriterion("updateUser like", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserNotLike(String value) {
            addCriterion("updateUser not like", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserIn(List<String> values) {
            addCriterion("updateUser in", values, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserNotIn(List<String> values) {
            addCriterion("updateUser not in", values, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserBetween(String value1, String value2) {
            addCriterion("updateUser between", value1, value2, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserNotBetween(String value1, String value2) {
            addCriterion("updateUser not between", value1, value2, "updateuser");
            return (Criteria) this;
        }

        public Criteria andEnvironmentIsNull() {
            addCriterion("environment is null");
            return (Criteria) this;
        }

        public Criteria andEnvironmentIsNotNull() {
            addCriterion("environment is not null");
            return (Criteria) this;
        }

        public Criteria andEnvironmentEqualTo(String value) {
            addCriterion("environment =", value, "environment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentNotEqualTo(String value) {
            addCriterion("environment <>", value, "environment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentGreaterThan(String value) {
            addCriterion("environment >", value, "environment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentGreaterThanOrEqualTo(String value) {
            addCriterion("environment >=", value, "environment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentLessThan(String value) {
            addCriterion("environment <", value, "environment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentLessThanOrEqualTo(String value) {
            addCriterion("environment <=", value, "environment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentLike(String value) {
            addCriterion("environment like", value, "environment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentNotLike(String value) {
            addCriterion("environment not like", value, "environment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentIn(List<String> values) {
            addCriterion("environment in", values, "environment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentNotIn(List<String> values) {
            addCriterion("environment not in", values, "environment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentBetween(String value1, String value2) {
            addCriterion("environment between", value1, value2, "environment");
            return (Criteria) this;
        }

        public Criteria andEnvironmentNotBetween(String value1, String value2) {
            addCriterion("environment not between", value1, value2, "environment");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cibr_stock_drosophila
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cibr_stock_drosophila
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}