package com.cibr.animal.demo.entity;

import java.util.Date;
import java.util.List;

public class CibrSysSuggest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_suggest.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_suggest.creater
     *
     * @mbggenerated
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_suggest.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_suggest.replyto
     *
     * @mbggenerated
     */
    private String replyto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_suggest.flag
     *
     * @mbggenerated
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_sys_suggest.comments
     *
     * @mbggenerated
     */
    private String comments;

    private CibrSysUser user;

    private List<CibrSysSuggest> replys;

    public CibrSysUser getUser() {
        return user;
    }

    public void setUser(CibrSysUser user) {
        this.user = user;
    }

    public List<CibrSysSuggest> getReplys() {
        return replys;
    }

    public void setReplys(List<CibrSysSuggest> replys) {
        this.replys = replys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_suggest.id
     *
     * @return the value of cibr_sys_suggest.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_suggest.id
     *
     * @param id the value for cibr_sys_suggest.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_suggest.creater
     *
     * @return the value of cibr_sys_suggest.creater
     *
     * @mbggenerated
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_suggest.creater
     *
     * @param creater the value for cibr_sys_suggest.creater
     *
     * @mbggenerated
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_suggest.createTime
     *
     * @return the value of cibr_sys_suggest.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_suggest.createTime
     *
     * @param createtime the value for cibr_sys_suggest.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_suggest.replyto
     *
     * @return the value of cibr_sys_suggest.replyto
     *
     * @mbggenerated
     */
    public String getReplyto() {
        return replyto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_suggest.replyto
     *
     * @param replyto the value for cibr_sys_suggest.replyto
     *
     * @mbggenerated
     */
    public void setReplyto(String replyto) {
        this.replyto = replyto == null ? null : replyto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_suggest.flag
     *
     * @return the value of cibr_sys_suggest.flag
     *
     * @mbggenerated
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_suggest.flag
     *
     * @param flag the value for cibr_sys_suggest.flag
     *
     * @mbggenerated
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_sys_suggest.comments
     *
     * @return the value of cibr_sys_suggest.comments
     *
     * @mbggenerated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_sys_suggest.comments
     *
     * @param comments the value for cibr_sys_suggest.comments
     *
     * @mbggenerated
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }
}