package com.cibr.animal.demo.entity;

import java.math.BigDecimal;
import java.util.Date;

public class CibrConfigPrice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_config_price.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_config_price.priceName
     *
     * @mbggenerated
     */
    private String pricename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_config_price.libtype
     *
     * @mbggenerated
     */
    private String libtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_config_price.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_config_price.pricetype
     *
     * @mbggenerated
     */
    private String pricetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_config_price.creater
     *
     * @mbggenerated
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_config_price.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_config_price.id
     *
     * @return the value of cibr_config_price.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_config_price.id
     *
     * @param id the value for cibr_config_price.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_config_price.priceName
     *
     * @return the value of cibr_config_price.priceName
     *
     * @mbggenerated
     */
    public String getPricename() {
        return pricename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_config_price.priceName
     *
     * @param pricename the value for cibr_config_price.priceName
     *
     * @mbggenerated
     */
    public void setPricename(String pricename) {
        this.pricename = pricename == null ? null : pricename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_config_price.libtype
     *
     * @return the value of cibr_config_price.libtype
     *
     * @mbggenerated
     */
    public String getLibtype() {
        return libtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_config_price.libtype
     *
     * @param libtype the value for cibr_config_price.libtype
     *
     * @mbggenerated
     */
    public void setLibtype(String libtype) {
        this.libtype = libtype == null ? null : libtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_config_price.price
     *
     * @return the value of cibr_config_price.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_config_price.price
     *
     * @param price the value for cibr_config_price.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_config_price.pricetype
     *
     * @return the value of cibr_config_price.pricetype
     *
     * @mbggenerated
     */
    public String getPricetype() {
        return pricetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_config_price.pricetype
     *
     * @param pricetype the value for cibr_config_price.pricetype
     *
     * @mbggenerated
     */
    public void setPricetype(String pricetype) {
        this.pricetype = pricetype == null ? null : pricetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_config_price.creater
     *
     * @return the value of cibr_config_price.creater
     *
     * @mbggenerated
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_config_price.creater
     *
     * @param creater the value for cibr_config_price.creater
     *
     * @mbggenerated
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_config_price.createTime
     *
     * @return the value of cibr_config_price.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_config_price.createTime
     *
     * @param createtime the value for cibr_config_price.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}