package com.cibr.animal.demo.entity;

import java.util.Date;

public class CibrTaskProcessSamplemake {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_samplemake.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_samplemake.processId
     *
     * @mbggenerated
     */
    private String processid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_samplemake.inputId
     *
     * @mbggenerated
     */
    private String inputid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_samplemake.sampleName
     *
     * @mbggenerated
     */
    private String samplename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_samplemake.selfNumber
     *
     * @mbggenerated
     */
    private String selfnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_samplemake.species
     *
     * @mbggenerated
     */
    private String species;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_samplemake.tissue
     *
     * @mbggenerated
     */
    private String tissue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_samplemake.testDate
     *
     * @mbggenerated
     */
    private Date testdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_samplemake.concentration
     *
     * @mbggenerated
     */
    private String concentration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_samplemake.sampleVolume
     *
     * @mbggenerated
     */
    private String samplevolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_samplemake.totalNumber
     *
     * @mbggenerated
     */
    private String totalnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_samplemake.cellLife
     *
     * @mbggenerated
     */
    private String celllife;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_samplemake.cellSort
     *
     * @mbggenerated
     */
    private String cellsort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_samplemake.extractMethod
     *
     * @mbggenerated
     */
    private String extractmethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_samplemake.checkResult
     *
     * @mbggenerated
     */
    private String checkresult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_samplemake.checkRemarks
     *
     * @mbggenerated
     */
    private String checkremarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_samplemake.checkUser
     *
     * @mbggenerated
     */
    private String checkuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_samplemake.reviewer
     *
     * @mbggenerated
     */
    private String reviewer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_samplemake.databaseType
     *
     * @mbggenerated
     */
    private String databasetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_samplemake.sequencingPlatform
     *
     * @mbggenerated
     */
    private String sequencingplatform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_samplemake.remaining
     *
     * @mbggenerated
     */
    private String remaining;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_samplemake.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_samplemake.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_samplemake.creater
     *
     * @mbggenerated
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_samplemake.currentStatu
     *
     * @mbggenerated
     */
    private String currentstatu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_samplemake.rowIndex
     *
     * @mbggenerated
     */
    private String rowindex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_samplemake.confirmTime
     *
     * @mbggenerated
     */
    private Date confirmtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_samplemake.confirmer
     *
     * @mbggenerated
     */
    private String confirmer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_samplemake.id
     *
     * @return the value of cibr_task_process_samplemake.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_samplemake.id
     *
     * @param id the value for cibr_task_process_samplemake.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_samplemake.processId
     *
     * @return the value of cibr_task_process_samplemake.processId
     *
     * @mbggenerated
     */
    public String getProcessid() {
        return processid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_samplemake.processId
     *
     * @param processid the value for cibr_task_process_samplemake.processId
     *
     * @mbggenerated
     */
    public void setProcessid(String processid) {
        this.processid = processid == null ? null : processid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_samplemake.inputId
     *
     * @return the value of cibr_task_process_samplemake.inputId
     *
     * @mbggenerated
     */
    public String getInputid() {
        return inputid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_samplemake.inputId
     *
     * @param inputid the value for cibr_task_process_samplemake.inputId
     *
     * @mbggenerated
     */
    public void setInputid(String inputid) {
        this.inputid = inputid == null ? null : inputid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_samplemake.sampleName
     *
     * @return the value of cibr_task_process_samplemake.sampleName
     *
     * @mbggenerated
     */
    public String getSamplename() {
        return samplename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_samplemake.sampleName
     *
     * @param samplename the value for cibr_task_process_samplemake.sampleName
     *
     * @mbggenerated
     */
    public void setSamplename(String samplename) {
        this.samplename = samplename == null ? null : samplename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_samplemake.selfNumber
     *
     * @return the value of cibr_task_process_samplemake.selfNumber
     *
     * @mbggenerated
     */
    public String getSelfnumber() {
        return selfnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_samplemake.selfNumber
     *
     * @param selfnumber the value for cibr_task_process_samplemake.selfNumber
     *
     * @mbggenerated
     */
    public void setSelfnumber(String selfnumber) {
        this.selfnumber = selfnumber == null ? null : selfnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_samplemake.species
     *
     * @return the value of cibr_task_process_samplemake.species
     *
     * @mbggenerated
     */
    public String getSpecies() {
        return species;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_samplemake.species
     *
     * @param species the value for cibr_task_process_samplemake.species
     *
     * @mbggenerated
     */
    public void setSpecies(String species) {
        this.species = species == null ? null : species.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_samplemake.tissue
     *
     * @return the value of cibr_task_process_samplemake.tissue
     *
     * @mbggenerated
     */
    public String getTissue() {
        return tissue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_samplemake.tissue
     *
     * @param tissue the value for cibr_task_process_samplemake.tissue
     *
     * @mbggenerated
     */
    public void setTissue(String tissue) {
        this.tissue = tissue == null ? null : tissue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_samplemake.testDate
     *
     * @return the value of cibr_task_process_samplemake.testDate
     *
     * @mbggenerated
     */
    public Date getTestdate() {
        return testdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_samplemake.testDate
     *
     * @param testdate the value for cibr_task_process_samplemake.testDate
     *
     * @mbggenerated
     */
    public void setTestdate(Date testdate) {
        this.testdate = testdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_samplemake.concentration
     *
     * @return the value of cibr_task_process_samplemake.concentration
     *
     * @mbggenerated
     */
    public String getConcentration() {
        return concentration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_samplemake.concentration
     *
     * @param concentration the value for cibr_task_process_samplemake.concentration
     *
     * @mbggenerated
     */
    public void setConcentration(String concentration) {
        this.concentration = concentration == null ? null : concentration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_samplemake.sampleVolume
     *
     * @return the value of cibr_task_process_samplemake.sampleVolume
     *
     * @mbggenerated
     */
    public String getSamplevolume() {
        return samplevolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_samplemake.sampleVolume
     *
     * @param samplevolume the value for cibr_task_process_samplemake.sampleVolume
     *
     * @mbggenerated
     */
    public void setSamplevolume(String samplevolume) {
        this.samplevolume = samplevolume == null ? null : samplevolume.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_samplemake.totalNumber
     *
     * @return the value of cibr_task_process_samplemake.totalNumber
     *
     * @mbggenerated
     */
    public String getTotalnumber() {
        return totalnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_samplemake.totalNumber
     *
     * @param totalnumber the value for cibr_task_process_samplemake.totalNumber
     *
     * @mbggenerated
     */
    public void setTotalnumber(String totalnumber) {
        this.totalnumber = totalnumber == null ? null : totalnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_samplemake.cellLife
     *
     * @return the value of cibr_task_process_samplemake.cellLife
     *
     * @mbggenerated
     */
    public String getCelllife() {
        return celllife;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_samplemake.cellLife
     *
     * @param celllife the value for cibr_task_process_samplemake.cellLife
     *
     * @mbggenerated
     */
    public void setCelllife(String celllife) {
        this.celllife = celllife == null ? null : celllife.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_samplemake.cellSort
     *
     * @return the value of cibr_task_process_samplemake.cellSort
     *
     * @mbggenerated
     */
    public String getCellsort() {
        return cellsort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_samplemake.cellSort
     *
     * @param cellsort the value for cibr_task_process_samplemake.cellSort
     *
     * @mbggenerated
     */
    public void setCellsort(String cellsort) {
        this.cellsort = cellsort == null ? null : cellsort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_samplemake.extractMethod
     *
     * @return the value of cibr_task_process_samplemake.extractMethod
     *
     * @mbggenerated
     */
    public String getExtractmethod() {
        return extractmethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_samplemake.extractMethod
     *
     * @param extractmethod the value for cibr_task_process_samplemake.extractMethod
     *
     * @mbggenerated
     */
    public void setExtractmethod(String extractmethod) {
        this.extractmethod = extractmethod == null ? null : extractmethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_samplemake.checkResult
     *
     * @return the value of cibr_task_process_samplemake.checkResult
     *
     * @mbggenerated
     */
    public String getCheckresult() {
        return checkresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_samplemake.checkResult
     *
     * @param checkresult the value for cibr_task_process_samplemake.checkResult
     *
     * @mbggenerated
     */
    public void setCheckresult(String checkresult) {
        this.checkresult = checkresult == null ? null : checkresult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_samplemake.checkRemarks
     *
     * @return the value of cibr_task_process_samplemake.checkRemarks
     *
     * @mbggenerated
     */
    public String getCheckremarks() {
        return checkremarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_samplemake.checkRemarks
     *
     * @param checkremarks the value for cibr_task_process_samplemake.checkRemarks
     *
     * @mbggenerated
     */
    public void setCheckremarks(String checkremarks) {
        this.checkremarks = checkremarks == null ? null : checkremarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_samplemake.checkUser
     *
     * @return the value of cibr_task_process_samplemake.checkUser
     *
     * @mbggenerated
     */
    public String getCheckuser() {
        return checkuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_samplemake.checkUser
     *
     * @param checkuser the value for cibr_task_process_samplemake.checkUser
     *
     * @mbggenerated
     */
    public void setCheckuser(String checkuser) {
        this.checkuser = checkuser == null ? null : checkuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_samplemake.reviewer
     *
     * @return the value of cibr_task_process_samplemake.reviewer
     *
     * @mbggenerated
     */
    public String getReviewer() {
        return reviewer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_samplemake.reviewer
     *
     * @param reviewer the value for cibr_task_process_samplemake.reviewer
     *
     * @mbggenerated
     */
    public void setReviewer(String reviewer) {
        this.reviewer = reviewer == null ? null : reviewer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_samplemake.databaseType
     *
     * @return the value of cibr_task_process_samplemake.databaseType
     *
     * @mbggenerated
     */
    public String getDatabasetype() {
        return databasetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_samplemake.databaseType
     *
     * @param databasetype the value for cibr_task_process_samplemake.databaseType
     *
     * @mbggenerated
     */
    public void setDatabasetype(String databasetype) {
        this.databasetype = databasetype == null ? null : databasetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_samplemake.sequencingPlatform
     *
     * @return the value of cibr_task_process_samplemake.sequencingPlatform
     *
     * @mbggenerated
     */
    public String getSequencingplatform() {
        return sequencingplatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_samplemake.sequencingPlatform
     *
     * @param sequencingplatform the value for cibr_task_process_samplemake.sequencingPlatform
     *
     * @mbggenerated
     */
    public void setSequencingplatform(String sequencingplatform) {
        this.sequencingplatform = sequencingplatform == null ? null : sequencingplatform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_samplemake.remaining
     *
     * @return the value of cibr_task_process_samplemake.remaining
     *
     * @mbggenerated
     */
    public String getRemaining() {
        return remaining;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_samplemake.remaining
     *
     * @param remaining the value for cibr_task_process_samplemake.remaining
     *
     * @mbggenerated
     */
    public void setRemaining(String remaining) {
        this.remaining = remaining == null ? null : remaining.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_samplemake.remarks
     *
     * @return the value of cibr_task_process_samplemake.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_samplemake.remarks
     *
     * @param remarks the value for cibr_task_process_samplemake.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_samplemake.createTime
     *
     * @return the value of cibr_task_process_samplemake.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_samplemake.createTime
     *
     * @param createtime the value for cibr_task_process_samplemake.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_samplemake.creater
     *
     * @return the value of cibr_task_process_samplemake.creater
     *
     * @mbggenerated
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_samplemake.creater
     *
     * @param creater the value for cibr_task_process_samplemake.creater
     *
     * @mbggenerated
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_samplemake.currentStatu
     *
     * @return the value of cibr_task_process_samplemake.currentStatu
     *
     * @mbggenerated
     */
    public String getCurrentstatu() {
        return currentstatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_samplemake.currentStatu
     *
     * @param currentstatu the value for cibr_task_process_samplemake.currentStatu
     *
     * @mbggenerated
     */
    public void setCurrentstatu(String currentstatu) {
        this.currentstatu = currentstatu == null ? null : currentstatu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_samplemake.rowIndex
     *
     * @return the value of cibr_task_process_samplemake.rowIndex
     *
     * @mbggenerated
     */
    public String getRowindex() {
        return rowindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_samplemake.rowIndex
     *
     * @param rowindex the value for cibr_task_process_samplemake.rowIndex
     *
     * @mbggenerated
     */
    public void setRowindex(String rowindex) {
        this.rowindex = rowindex == null ? null : rowindex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_samplemake.confirmTime
     *
     * @return the value of cibr_task_process_samplemake.confirmTime
     *
     * @mbggenerated
     */
    public Date getConfirmtime() {
        return confirmtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_samplemake.confirmTime
     *
     * @param confirmtime the value for cibr_task_process_samplemake.confirmTime
     *
     * @mbggenerated
     */
    public void setConfirmtime(Date confirmtime) {
        this.confirmtime = confirmtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_samplemake.confirmer
     *
     * @return the value of cibr_task_process_samplemake.confirmer
     *
     * @mbggenerated
     */
    public String getConfirmer() {
        return confirmer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_samplemake.confirmer
     *
     * @param confirmer the value for cibr_task_process_samplemake.confirmer
     *
     * @mbggenerated
     */
    public void setConfirmer(String confirmer) {
        this.confirmer = confirmer == null ? null : confirmer.trim();
    }
}