package com.cibr.animal.demo.entity;

import java.util.Date;
import java.util.List;

public class CibrTaskProcessDiystatu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_diystatu.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_diystatu.diyName
     *
     * @mbggenerated
     */
    private String diyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_diystatu.diystatu
     *
     * @mbggenerated
     */
    private String diystatu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_diystatu.connectSample
     *
     * @mbggenerated
     */
    private String connectsample;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_diystatu.curstatu
     *
     * @mbggenerated
     */
    private String curstatu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_diystatu.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_diystatu.creater
     *
     * @mbggenerated
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_diystatu.processId
     *
     * @mbggenerated
     */
    private String processid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_diystatu.updateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_diystatu.updater
     *
     * @mbggenerated
     */
    private String updater;

    private List<String> inputs;

    public List<String> getInputs() {
        return inputs;
    }

    public void setInputs(List<String> inputs) {
        this.inputs = inputs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_diystatu.id
     *
     * @return the value of cibr_task_process_diystatu.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_diystatu.id
     *
     * @param id the value for cibr_task_process_diystatu.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_diystatu.diyName
     *
     * @return the value of cibr_task_process_diystatu.diyName
     *
     * @mbggenerated
     */
    public String getDiyname() {
        return diyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_diystatu.diyName
     *
     * @param diyname the value for cibr_task_process_diystatu.diyName
     *
     * @mbggenerated
     */
    public void setDiyname(String diyname) {
        this.diyname = diyname == null ? null : diyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_diystatu.diystatu
     *
     * @return the value of cibr_task_process_diystatu.diystatu
     *
     * @mbggenerated
     */
    public String getDiystatu() {
        return diystatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_diystatu.diystatu
     *
     * @param diystatu the value for cibr_task_process_diystatu.diystatu
     *
     * @mbggenerated
     */
    public void setDiystatu(String diystatu) {
        this.diystatu = diystatu == null ? null : diystatu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_diystatu.connectSample
     *
     * @return the value of cibr_task_process_diystatu.connectSample
     *
     * @mbggenerated
     */
    public String getConnectsample() {
        return connectsample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_diystatu.connectSample
     *
     * @param connectsample the value for cibr_task_process_diystatu.connectSample
     *
     * @mbggenerated
     */
    public void setConnectsample(String connectsample) {
        this.connectsample = connectsample == null ? null : connectsample.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_diystatu.curstatu
     *
     * @return the value of cibr_task_process_diystatu.curstatu
     *
     * @mbggenerated
     */
    public String getCurstatu() {
        return curstatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_diystatu.curstatu
     *
     * @param curstatu the value for cibr_task_process_diystatu.curstatu
     *
     * @mbggenerated
     */
    public void setCurstatu(String curstatu) {
        this.curstatu = curstatu == null ? null : curstatu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_diystatu.createTime
     *
     * @return the value of cibr_task_process_diystatu.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_diystatu.createTime
     *
     * @param createtime the value for cibr_task_process_diystatu.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_diystatu.creater
     *
     * @return the value of cibr_task_process_diystatu.creater
     *
     * @mbggenerated
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_diystatu.creater
     *
     * @param creater the value for cibr_task_process_diystatu.creater
     *
     * @mbggenerated
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_diystatu.processId
     *
     * @return the value of cibr_task_process_diystatu.processId
     *
     * @mbggenerated
     */
    public String getProcessid() {
        return processid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_diystatu.processId
     *
     * @param processid the value for cibr_task_process_diystatu.processId
     *
     * @mbggenerated
     */
    public void setProcessid(String processid) {
        this.processid = processid == null ? null : processid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_diystatu.updateTime
     *
     * @return the value of cibr_task_process_diystatu.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_diystatu.updateTime
     *
     * @param updatetime the value for cibr_task_process_diystatu.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_diystatu.updater
     *
     * @return the value of cibr_task_process_diystatu.updater
     *
     * @mbggenerated
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_diystatu.updater
     *
     * @param updater the value for cibr_task_process_diystatu.updater
     *
     * @mbggenerated
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }
}