package com.cibr.animal.demo.entity;

import java.math.BigDecimal;
import java.util.Date;

public class CibrBillGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_bill_group.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_bill_group.groupId
     *
     * @mbggenerated
     */
    private String groupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_bill_group.groupName
     *
     * @mbggenerated
     */
    private String groupname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_bill_group.extractCost
     *
     * @mbggenerated
     */
    private BigDecimal extractcost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_bill_group.detectCost
     *
     * @mbggenerated
     */
    private BigDecimal detectcost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_bill_group.libdbCost
     *
     * @mbggenerated
     */
    private BigDecimal libdbcost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_bill_group.seqCost
     *
     * @mbggenerated
     */
    private BigDecimal seqcost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_bill_group.totalCost
     *
     * @mbggenerated
     */
    private BigDecimal totalcost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_bill_group.creater
     *
     * @mbggenerated
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_bill_group.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_bill_group.updater
     *
     * @mbggenerated
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_bill_group.updateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_bill_group.currentMonth
     *
     * @mbggenerated
     */
    private String currentmonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_bill_group.curentStatu
     *
     * @mbggenerated
     */
    private String curentstatu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_bill_group.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_bill_group.id
     *
     * @return the value of cibr_bill_group.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_bill_group.id
     *
     * @param id the value for cibr_bill_group.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_bill_group.groupId
     *
     * @return the value of cibr_bill_group.groupId
     *
     * @mbggenerated
     */
    public String getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_bill_group.groupId
     *
     * @param groupid the value for cibr_bill_group.groupId
     *
     * @mbggenerated
     */
    public void setGroupid(String groupid) {
        this.groupid = groupid == null ? null : groupid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_bill_group.groupName
     *
     * @return the value of cibr_bill_group.groupName
     *
     * @mbggenerated
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_bill_group.groupName
     *
     * @param groupname the value for cibr_bill_group.groupName
     *
     * @mbggenerated
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname == null ? null : groupname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_bill_group.extractCost
     *
     * @return the value of cibr_bill_group.extractCost
     *
     * @mbggenerated
     */
    public BigDecimal getExtractcost() {
        return extractcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_bill_group.extractCost
     *
     * @param extractcost the value for cibr_bill_group.extractCost
     *
     * @mbggenerated
     */
    public void setExtractcost(BigDecimal extractcost) {
        this.extractcost = extractcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_bill_group.detectCost
     *
     * @return the value of cibr_bill_group.detectCost
     *
     * @mbggenerated
     */
    public BigDecimal getDetectcost() {
        return detectcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_bill_group.detectCost
     *
     * @param detectcost the value for cibr_bill_group.detectCost
     *
     * @mbggenerated
     */
    public void setDetectcost(BigDecimal detectcost) {
        this.detectcost = detectcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_bill_group.libdbCost
     *
     * @return the value of cibr_bill_group.libdbCost
     *
     * @mbggenerated
     */
    public BigDecimal getLibdbcost() {
        return libdbcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_bill_group.libdbCost
     *
     * @param libdbcost the value for cibr_bill_group.libdbCost
     *
     * @mbggenerated
     */
    public void setLibdbcost(BigDecimal libdbcost) {
        this.libdbcost = libdbcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_bill_group.seqCost
     *
     * @return the value of cibr_bill_group.seqCost
     *
     * @mbggenerated
     */
    public BigDecimal getSeqcost() {
        return seqcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_bill_group.seqCost
     *
     * @param seqcost the value for cibr_bill_group.seqCost
     *
     * @mbggenerated
     */
    public void setSeqcost(BigDecimal seqcost) {
        this.seqcost = seqcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_bill_group.totalCost
     *
     * @return the value of cibr_bill_group.totalCost
     *
     * @mbggenerated
     */
    public BigDecimal getTotalcost() {
        return totalcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_bill_group.totalCost
     *
     * @param totalcost the value for cibr_bill_group.totalCost
     *
     * @mbggenerated
     */
    public void setTotalcost(BigDecimal totalcost) {
        this.totalcost = totalcost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_bill_group.creater
     *
     * @return the value of cibr_bill_group.creater
     *
     * @mbggenerated
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_bill_group.creater
     *
     * @param creater the value for cibr_bill_group.creater
     *
     * @mbggenerated
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_bill_group.createTime
     *
     * @return the value of cibr_bill_group.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_bill_group.createTime
     *
     * @param createtime the value for cibr_bill_group.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_bill_group.updater
     *
     * @return the value of cibr_bill_group.updater
     *
     * @mbggenerated
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_bill_group.updater
     *
     * @param updater the value for cibr_bill_group.updater
     *
     * @mbggenerated
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_bill_group.updateTime
     *
     * @return the value of cibr_bill_group.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_bill_group.updateTime
     *
     * @param updatetime the value for cibr_bill_group.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_bill_group.currentMonth
     *
     * @return the value of cibr_bill_group.currentMonth
     *
     * @mbggenerated
     */
    public String getCurrentmonth() {
        return currentmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_bill_group.currentMonth
     *
     * @param currentmonth the value for cibr_bill_group.currentMonth
     *
     * @mbggenerated
     */
    public void setCurrentmonth(String currentmonth) {
        this.currentmonth = currentmonth == null ? null : currentmonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_bill_group.curentStatu
     *
     * @return the value of cibr_bill_group.curentStatu
     *
     * @mbggenerated
     */
    public String getCurentstatu() {
        return curentstatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_bill_group.curentStatu
     *
     * @param curentstatu the value for cibr_bill_group.curentStatu
     *
     * @mbggenerated
     */
    public void setCurentstatu(String curentstatu) {
        this.curentstatu = curentstatu == null ? null : curentstatu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_bill_group.remark
     *
     * @return the value of cibr_bill_group.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_bill_group.remark
     *
     * @param remark the value for cibr_bill_group.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}