package com.cibr.animal.demo.entity;

import java.util.Date;

public class CibrTaskProcessAnalysis {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_analysis.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_analysis.processId
     *
     * @mbggenerated
     */
    private String processid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_analysis.subId
     *
     * @mbggenerated
     */
    private String subid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_analysis.dismountId
     *
     * @mbggenerated
     */
    private String dismountid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_analysis.sampleName
     *
     * @mbggenerated
     */
    private String samplename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_analysis.species
     *
     * @mbggenerated
     */
    private String species;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_analysis.tissue
     *
     * @mbggenerated
     */
    private String tissue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_analysis.sampleIndex
     *
     * @mbggenerated
     */
    private String sampleindex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_analysis.resultPath
     *
     * @mbggenerated
     */
    private String resultpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_analysis.reportPath
     *
     * @mbggenerated
     */
    private String reportpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_analysis.args
     *
     * @mbggenerated
     */
    private String args;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_analysis.analyst
     *
     * @mbggenerated
     */
    private String analyst;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_analysis.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_analysis.currentStatu
     *
     * @mbggenerated
     */
    private String currentstatu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_analysis.creater
     *
     * @mbggenerated
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_analysis.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_analysis.rowIndex
     *
     * @mbggenerated
     */
    private Integer rowindex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_analysis.updateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_analysis.updateUser
     *
     * @mbggenerated
     */
    private String updateuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_analysis.id
     *
     * @return the value of cibr_task_process_analysis.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_analysis.id
     *
     * @param id the value for cibr_task_process_analysis.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_analysis.processId
     *
     * @return the value of cibr_task_process_analysis.processId
     *
     * @mbggenerated
     */
    public String getProcessid() {
        return processid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_analysis.processId
     *
     * @param processid the value for cibr_task_process_analysis.processId
     *
     * @mbggenerated
     */
    public void setProcessid(String processid) {
        this.processid = processid == null ? null : processid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_analysis.subId
     *
     * @return the value of cibr_task_process_analysis.subId
     *
     * @mbggenerated
     */
    public String getSubid() {
        return subid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_analysis.subId
     *
     * @param subid the value for cibr_task_process_analysis.subId
     *
     * @mbggenerated
     */
    public void setSubid(String subid) {
        this.subid = subid == null ? null : subid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_analysis.dismountId
     *
     * @return the value of cibr_task_process_analysis.dismountId
     *
     * @mbggenerated
     */
    public String getDismountid() {
        return dismountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_analysis.dismountId
     *
     * @param dismountid the value for cibr_task_process_analysis.dismountId
     *
     * @mbggenerated
     */
    public void setDismountid(String dismountid) {
        this.dismountid = dismountid == null ? null : dismountid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_analysis.sampleName
     *
     * @return the value of cibr_task_process_analysis.sampleName
     *
     * @mbggenerated
     */
    public String getSamplename() {
        return samplename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_analysis.sampleName
     *
     * @param samplename the value for cibr_task_process_analysis.sampleName
     *
     * @mbggenerated
     */
    public void setSamplename(String samplename) {
        this.samplename = samplename == null ? null : samplename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_analysis.species
     *
     * @return the value of cibr_task_process_analysis.species
     *
     * @mbggenerated
     */
    public String getSpecies() {
        return species;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_analysis.species
     *
     * @param species the value for cibr_task_process_analysis.species
     *
     * @mbggenerated
     */
    public void setSpecies(String species) {
        this.species = species == null ? null : species.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_analysis.tissue
     *
     * @return the value of cibr_task_process_analysis.tissue
     *
     * @mbggenerated
     */
    public String getTissue() {
        return tissue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_analysis.tissue
     *
     * @param tissue the value for cibr_task_process_analysis.tissue
     *
     * @mbggenerated
     */
    public void setTissue(String tissue) {
        this.tissue = tissue == null ? null : tissue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_analysis.sampleIndex
     *
     * @return the value of cibr_task_process_analysis.sampleIndex
     *
     * @mbggenerated
     */
    public String getSampleindex() {
        return sampleindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_analysis.sampleIndex
     *
     * @param sampleindex the value for cibr_task_process_analysis.sampleIndex
     *
     * @mbggenerated
     */
    public void setSampleindex(String sampleindex) {
        this.sampleindex = sampleindex == null ? null : sampleindex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_analysis.resultPath
     *
     * @return the value of cibr_task_process_analysis.resultPath
     *
     * @mbggenerated
     */
    public String getResultpath() {
        return resultpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_analysis.resultPath
     *
     * @param resultpath the value for cibr_task_process_analysis.resultPath
     *
     * @mbggenerated
     */
    public void setResultpath(String resultpath) {
        this.resultpath = resultpath == null ? null : resultpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_analysis.reportPath
     *
     * @return the value of cibr_task_process_analysis.reportPath
     *
     * @mbggenerated
     */
    public String getReportpath() {
        return reportpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_analysis.reportPath
     *
     * @param reportpath the value for cibr_task_process_analysis.reportPath
     *
     * @mbggenerated
     */
    public void setReportpath(String reportpath) {
        this.reportpath = reportpath == null ? null : reportpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_analysis.args
     *
     * @return the value of cibr_task_process_analysis.args
     *
     * @mbggenerated
     */
    public String getArgs() {
        return args;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_analysis.args
     *
     * @param args the value for cibr_task_process_analysis.args
     *
     * @mbggenerated
     */
    public void setArgs(String args) {
        this.args = args == null ? null : args.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_analysis.analyst
     *
     * @return the value of cibr_task_process_analysis.analyst
     *
     * @mbggenerated
     */
    public String getAnalyst() {
        return analyst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_analysis.analyst
     *
     * @param analyst the value for cibr_task_process_analysis.analyst
     *
     * @mbggenerated
     */
    public void setAnalyst(String analyst) {
        this.analyst = analyst == null ? null : analyst.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_analysis.remarks
     *
     * @return the value of cibr_task_process_analysis.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_analysis.remarks
     *
     * @param remarks the value for cibr_task_process_analysis.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_analysis.currentStatu
     *
     * @return the value of cibr_task_process_analysis.currentStatu
     *
     * @mbggenerated
     */
    public String getCurrentstatu() {
        return currentstatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_analysis.currentStatu
     *
     * @param currentstatu the value for cibr_task_process_analysis.currentStatu
     *
     * @mbggenerated
     */
    public void setCurrentstatu(String currentstatu) {
        this.currentstatu = currentstatu == null ? null : currentstatu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_analysis.creater
     *
     * @return the value of cibr_task_process_analysis.creater
     *
     * @mbggenerated
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_analysis.creater
     *
     * @param creater the value for cibr_task_process_analysis.creater
     *
     * @mbggenerated
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_analysis.createTime
     *
     * @return the value of cibr_task_process_analysis.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_analysis.createTime
     *
     * @param createtime the value for cibr_task_process_analysis.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_analysis.rowIndex
     *
     * @return the value of cibr_task_process_analysis.rowIndex
     *
     * @mbggenerated
     */
    public Integer getRowindex() {
        return rowindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_analysis.rowIndex
     *
     * @param rowindex the value for cibr_task_process_analysis.rowIndex
     *
     * @mbggenerated
     */
    public void setRowindex(Integer rowindex) {
        this.rowindex = rowindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_analysis.updateTime
     *
     * @return the value of cibr_task_process_analysis.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_analysis.updateTime
     *
     * @param updatetime the value for cibr_task_process_analysis.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_analysis.updateUser
     *
     * @return the value of cibr_task_process_analysis.updateUser
     *
     * @mbggenerated
     */
    public String getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_analysis.updateUser
     *
     * @param updateuser the value for cibr_task_process_analysis.updateUser
     *
     * @mbggenerated
     */
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser == null ? null : updateuser.trim();
    }
}