package com.cibr.animal.demo.entity;

import java.util.Date;

public class CibrTaskProcessSubtask {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_subtask.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_subtask.processId
     *
     * @mbggenerated
     */
    private String processid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_subtask.taskId
     *
     * @mbggenerated
     */
    private String taskid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_subtask.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_subtask.currentStatu
     *
     * @mbggenerated
     */
    private String currentstatu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_subtask.creater
     *
     * @mbggenerated
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_subtask.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_subtask.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_process_subtask.preId
     *
     * @mbggenerated
     */
    private String preid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_subtask.id
     *
     * @return the value of cibr_task_process_subtask.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_subtask.id
     *
     * @param id the value for cibr_task_process_subtask.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_subtask.processId
     *
     * @return the value of cibr_task_process_subtask.processId
     *
     * @mbggenerated
     */
    public String getProcessid() {
        return processid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_subtask.processId
     *
     * @param processid the value for cibr_task_process_subtask.processId
     *
     * @mbggenerated
     */
    public void setProcessid(String processid) {
        this.processid = processid == null ? null : processid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_subtask.taskId
     *
     * @return the value of cibr_task_process_subtask.taskId
     *
     * @mbggenerated
     */
    public String getTaskid() {
        return taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_subtask.taskId
     *
     * @param taskid the value for cibr_task_process_subtask.taskId
     *
     * @mbggenerated
     */
    public void setTaskid(String taskid) {
        this.taskid = taskid == null ? null : taskid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_subtask.name
     *
     * @return the value of cibr_task_process_subtask.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_subtask.name
     *
     * @param name the value for cibr_task_process_subtask.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_subtask.currentStatu
     *
     * @return the value of cibr_task_process_subtask.currentStatu
     *
     * @mbggenerated
     */
    public String getCurrentstatu() {
        return currentstatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_subtask.currentStatu
     *
     * @param currentstatu the value for cibr_task_process_subtask.currentStatu
     *
     * @mbggenerated
     */
    public void setCurrentstatu(String currentstatu) {
        this.currentstatu = currentstatu == null ? null : currentstatu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_subtask.creater
     *
     * @return the value of cibr_task_process_subtask.creater
     *
     * @mbggenerated
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_subtask.creater
     *
     * @param creater the value for cibr_task_process_subtask.creater
     *
     * @mbggenerated
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_subtask.createTime
     *
     * @return the value of cibr_task_process_subtask.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_subtask.createTime
     *
     * @param createtime the value for cibr_task_process_subtask.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_subtask.remarks
     *
     * @return the value of cibr_task_process_subtask.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_subtask.remarks
     *
     * @param remarks the value for cibr_task_process_subtask.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_process_subtask.preId
     *
     * @return the value of cibr_task_process_subtask.preId
     *
     * @mbggenerated
     */
    public String getPreid() {
        return preid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_process_subtask.preId
     *
     * @param preid the value for cibr_task_process_subtask.preId
     *
     * @mbggenerated
     */
    public void setPreid(String preid) {
        this.preid = preid == null ? null : preid.trim();
    }
}