package com.cibr.animal.demo.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CibrTaskProcessConfirmExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cibr_task_process_confirm
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cibr_task_process_confirm
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cibr_task_process_confirm
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_confirm
     *
     * @mbggenerated
     */
    public CibrTaskProcessConfirmExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_confirm
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_confirm
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_confirm
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_confirm
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_confirm
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_confirm
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_confirm
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_confirm
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_confirm
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_task_process_confirm
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cibr_task_process_confirm
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProcessidIsNull() {
            addCriterion("processId is null");
            return (Criteria) this;
        }

        public Criteria andProcessidIsNotNull() {
            addCriterion("processId is not null");
            return (Criteria) this;
        }

        public Criteria andProcessidEqualTo(String value) {
            addCriterion("processId =", value, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidNotEqualTo(String value) {
            addCriterion("processId <>", value, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidGreaterThan(String value) {
            addCriterion("processId >", value, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidGreaterThanOrEqualTo(String value) {
            addCriterion("processId >=", value, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidLessThan(String value) {
            addCriterion("processId <", value, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidLessThanOrEqualTo(String value) {
            addCriterion("processId <=", value, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidLike(String value) {
            addCriterion("processId like", value, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidNotLike(String value) {
            addCriterion("processId not like", value, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidIn(List<String> values) {
            addCriterion("processId in", values, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidNotIn(List<String> values) {
            addCriterion("processId not in", values, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidBetween(String value1, String value2) {
            addCriterion("processId between", value1, value2, "processid");
            return (Criteria) this;
        }

        public Criteria andProcessidNotBetween(String value1, String value2) {
            addCriterion("processId not between", value1, value2, "processid");
            return (Criteria) this;
        }

        public Criteria andLibidIsNull() {
            addCriterion("libId is null");
            return (Criteria) this;
        }

        public Criteria andLibidIsNotNull() {
            addCriterion("libId is not null");
            return (Criteria) this;
        }

        public Criteria andLibidEqualTo(String value) {
            addCriterion("libId =", value, "libid");
            return (Criteria) this;
        }

        public Criteria andLibidNotEqualTo(String value) {
            addCriterion("libId <>", value, "libid");
            return (Criteria) this;
        }

        public Criteria andLibidGreaterThan(String value) {
            addCriterion("libId >", value, "libid");
            return (Criteria) this;
        }

        public Criteria andLibidGreaterThanOrEqualTo(String value) {
            addCriterion("libId >=", value, "libid");
            return (Criteria) this;
        }

        public Criteria andLibidLessThan(String value) {
            addCriterion("libId <", value, "libid");
            return (Criteria) this;
        }

        public Criteria andLibidLessThanOrEqualTo(String value) {
            addCriterion("libId <=", value, "libid");
            return (Criteria) this;
        }

        public Criteria andLibidLike(String value) {
            addCriterion("libId like", value, "libid");
            return (Criteria) this;
        }

        public Criteria andLibidNotLike(String value) {
            addCriterion("libId not like", value, "libid");
            return (Criteria) this;
        }

        public Criteria andLibidIn(List<String> values) {
            addCriterion("libId in", values, "libid");
            return (Criteria) this;
        }

        public Criteria andLibidNotIn(List<String> values) {
            addCriterion("libId not in", values, "libid");
            return (Criteria) this;
        }

        public Criteria andLibidBetween(String value1, String value2) {
            addCriterion("libId between", value1, value2, "libid");
            return (Criteria) this;
        }

        public Criteria andLibidNotBetween(String value1, String value2) {
            addCriterion("libId not between", value1, value2, "libid");
            return (Criteria) this;
        }

        public Criteria andSamplenameIsNull() {
            addCriterion("sampleName is null");
            return (Criteria) this;
        }

        public Criteria andSamplenameIsNotNull() {
            addCriterion("sampleName is not null");
            return (Criteria) this;
        }

        public Criteria andSamplenameEqualTo(String value) {
            addCriterion("sampleName =", value, "samplename");
            return (Criteria) this;
        }

        public Criteria andSamplenameNotEqualTo(String value) {
            addCriterion("sampleName <>", value, "samplename");
            return (Criteria) this;
        }

        public Criteria andSamplenameGreaterThan(String value) {
            addCriterion("sampleName >", value, "samplename");
            return (Criteria) this;
        }

        public Criteria andSamplenameGreaterThanOrEqualTo(String value) {
            addCriterion("sampleName >=", value, "samplename");
            return (Criteria) this;
        }

        public Criteria andSamplenameLessThan(String value) {
            addCriterion("sampleName <", value, "samplename");
            return (Criteria) this;
        }

        public Criteria andSamplenameLessThanOrEqualTo(String value) {
            addCriterion("sampleName <=", value, "samplename");
            return (Criteria) this;
        }

        public Criteria andSamplenameLike(String value) {
            addCriterion("sampleName like", value, "samplename");
            return (Criteria) this;
        }

        public Criteria andSamplenameNotLike(String value) {
            addCriterion("sampleName not like", value, "samplename");
            return (Criteria) this;
        }

        public Criteria andSamplenameIn(List<String> values) {
            addCriterion("sampleName in", values, "samplename");
            return (Criteria) this;
        }

        public Criteria andSamplenameNotIn(List<String> values) {
            addCriterion("sampleName not in", values, "samplename");
            return (Criteria) this;
        }

        public Criteria andSamplenameBetween(String value1, String value2) {
            addCriterion("sampleName between", value1, value2, "samplename");
            return (Criteria) this;
        }

        public Criteria andSamplenameNotBetween(String value1, String value2) {
            addCriterion("sampleName not between", value1, value2, "samplename");
            return (Criteria) this;
        }

        public Criteria andInitsampleIsNull() {
            addCriterion("initSample is null");
            return (Criteria) this;
        }

        public Criteria andInitsampleIsNotNull() {
            addCriterion("initSample is not null");
            return (Criteria) this;
        }

        public Criteria andInitsampleEqualTo(String value) {
            addCriterion("initSample =", value, "initsample");
            return (Criteria) this;
        }

        public Criteria andInitsampleNotEqualTo(String value) {
            addCriterion("initSample <>", value, "initsample");
            return (Criteria) this;
        }

        public Criteria andInitsampleGreaterThan(String value) {
            addCriterion("initSample >", value, "initsample");
            return (Criteria) this;
        }

        public Criteria andInitsampleGreaterThanOrEqualTo(String value) {
            addCriterion("initSample >=", value, "initsample");
            return (Criteria) this;
        }

        public Criteria andInitsampleLessThan(String value) {
            addCriterion("initSample <", value, "initsample");
            return (Criteria) this;
        }

        public Criteria andInitsampleLessThanOrEqualTo(String value) {
            addCriterion("initSample <=", value, "initsample");
            return (Criteria) this;
        }

        public Criteria andInitsampleLike(String value) {
            addCriterion("initSample like", value, "initsample");
            return (Criteria) this;
        }

        public Criteria andInitsampleNotLike(String value) {
            addCriterion("initSample not like", value, "initsample");
            return (Criteria) this;
        }

        public Criteria andInitsampleIn(List<String> values) {
            addCriterion("initSample in", values, "initsample");
            return (Criteria) this;
        }

        public Criteria andInitsampleNotIn(List<String> values) {
            addCriterion("initSample not in", values, "initsample");
            return (Criteria) this;
        }

        public Criteria andInitsampleBetween(String value1, String value2) {
            addCriterion("initSample between", value1, value2, "initsample");
            return (Criteria) this;
        }

        public Criteria andInitsampleNotBetween(String value1, String value2) {
            addCriterion("initSample not between", value1, value2, "initsample");
            return (Criteria) this;
        }

        public Criteria andSampleindexIsNull() {
            addCriterion("sampleIndex is null");
            return (Criteria) this;
        }

        public Criteria andSampleindexIsNotNull() {
            addCriterion("sampleIndex is not null");
            return (Criteria) this;
        }

        public Criteria andSampleindexEqualTo(String value) {
            addCriterion("sampleIndex =", value, "sampleindex");
            return (Criteria) this;
        }

        public Criteria andSampleindexNotEqualTo(String value) {
            addCriterion("sampleIndex <>", value, "sampleindex");
            return (Criteria) this;
        }

        public Criteria andSampleindexGreaterThan(String value) {
            addCriterion("sampleIndex >", value, "sampleindex");
            return (Criteria) this;
        }

        public Criteria andSampleindexGreaterThanOrEqualTo(String value) {
            addCriterion("sampleIndex >=", value, "sampleindex");
            return (Criteria) this;
        }

        public Criteria andSampleindexLessThan(String value) {
            addCriterion("sampleIndex <", value, "sampleindex");
            return (Criteria) this;
        }

        public Criteria andSampleindexLessThanOrEqualTo(String value) {
            addCriterion("sampleIndex <=", value, "sampleindex");
            return (Criteria) this;
        }

        public Criteria andSampleindexLike(String value) {
            addCriterion("sampleIndex like", value, "sampleindex");
            return (Criteria) this;
        }

        public Criteria andSampleindexNotLike(String value) {
            addCriterion("sampleIndex not like", value, "sampleindex");
            return (Criteria) this;
        }

        public Criteria andSampleindexIn(List<String> values) {
            addCriterion("sampleIndex in", values, "sampleindex");
            return (Criteria) this;
        }

        public Criteria andSampleindexNotIn(List<String> values) {
            addCriterion("sampleIndex not in", values, "sampleindex");
            return (Criteria) this;
        }

        public Criteria andSampleindexBetween(String value1, String value2) {
            addCriterion("sampleIndex between", value1, value2, "sampleindex");
            return (Criteria) this;
        }

        public Criteria andSampleindexNotBetween(String value1, String value2) {
            addCriterion("sampleIndex not between", value1, value2, "sampleindex");
            return (Criteria) this;
        }

        public Criteria andLibindexIsNull() {
            addCriterion("libIndex is null");
            return (Criteria) this;
        }

        public Criteria andLibindexIsNotNull() {
            addCriterion("libIndex is not null");
            return (Criteria) this;
        }

        public Criteria andLibindexEqualTo(String value) {
            addCriterion("libIndex =", value, "libindex");
            return (Criteria) this;
        }

        public Criteria andLibindexNotEqualTo(String value) {
            addCriterion("libIndex <>", value, "libindex");
            return (Criteria) this;
        }

        public Criteria andLibindexGreaterThan(String value) {
            addCriterion("libIndex >", value, "libindex");
            return (Criteria) this;
        }

        public Criteria andLibindexGreaterThanOrEqualTo(String value) {
            addCriterion("libIndex >=", value, "libindex");
            return (Criteria) this;
        }

        public Criteria andLibindexLessThan(String value) {
            addCriterion("libIndex <", value, "libindex");
            return (Criteria) this;
        }

        public Criteria andLibindexLessThanOrEqualTo(String value) {
            addCriterion("libIndex <=", value, "libindex");
            return (Criteria) this;
        }

        public Criteria andLibindexLike(String value) {
            addCriterion("libIndex like", value, "libindex");
            return (Criteria) this;
        }

        public Criteria andLibindexNotLike(String value) {
            addCriterion("libIndex not like", value, "libindex");
            return (Criteria) this;
        }

        public Criteria andLibindexIn(List<String> values) {
            addCriterion("libIndex in", values, "libindex");
            return (Criteria) this;
        }

        public Criteria andLibindexNotIn(List<String> values) {
            addCriterion("libIndex not in", values, "libindex");
            return (Criteria) this;
        }

        public Criteria andLibindexBetween(String value1, String value2) {
            addCriterion("libIndex between", value1, value2, "libindex");
            return (Criteria) this;
        }

        public Criteria andLibindexNotBetween(String value1, String value2) {
            addCriterion("libIndex not between", value1, value2, "libindex");
            return (Criteria) this;
        }

        public Criteria andCreatedbtimeIsNull() {
            addCriterion("createDbTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatedbtimeIsNotNull() {
            addCriterion("createDbTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedbtimeEqualTo(Date value) {
            addCriterion("createDbTime =", value, "createdbtime");
            return (Criteria) this;
        }

        public Criteria andCreatedbtimeNotEqualTo(Date value) {
            addCriterion("createDbTime <>", value, "createdbtime");
            return (Criteria) this;
        }

        public Criteria andCreatedbtimeGreaterThan(Date value) {
            addCriterion("createDbTime >", value, "createdbtime");
            return (Criteria) this;
        }

        public Criteria andCreatedbtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createDbTime >=", value, "createdbtime");
            return (Criteria) this;
        }

        public Criteria andCreatedbtimeLessThan(Date value) {
            addCriterion("createDbTime <", value, "createdbtime");
            return (Criteria) this;
        }

        public Criteria andCreatedbtimeLessThanOrEqualTo(Date value) {
            addCriterion("createDbTime <=", value, "createdbtime");
            return (Criteria) this;
        }

        public Criteria andCreatedbtimeIn(List<Date> values) {
            addCriterion("createDbTime in", values, "createdbtime");
            return (Criteria) this;
        }

        public Criteria andCreatedbtimeNotIn(List<Date> values) {
            addCriterion("createDbTime not in", values, "createdbtime");
            return (Criteria) this;
        }

        public Criteria andCreatedbtimeBetween(Date value1, Date value2) {
            addCriterion("createDbTime between", value1, value2, "createdbtime");
            return (Criteria) this;
        }

        public Criteria andCreatedbtimeNotBetween(Date value1, Date value2) {
            addCriterion("createDbTime not between", value1, value2, "createdbtime");
            return (Criteria) this;
        }

        public Criteria andLibtypeIsNull() {
            addCriterion("libType is null");
            return (Criteria) this;
        }

        public Criteria andLibtypeIsNotNull() {
            addCriterion("libType is not null");
            return (Criteria) this;
        }

        public Criteria andLibtypeEqualTo(String value) {
            addCriterion("libType =", value, "libtype");
            return (Criteria) this;
        }

        public Criteria andLibtypeNotEqualTo(String value) {
            addCriterion("libType <>", value, "libtype");
            return (Criteria) this;
        }

        public Criteria andLibtypeGreaterThan(String value) {
            addCriterion("libType >", value, "libtype");
            return (Criteria) this;
        }

        public Criteria andLibtypeGreaterThanOrEqualTo(String value) {
            addCriterion("libType >=", value, "libtype");
            return (Criteria) this;
        }

        public Criteria andLibtypeLessThan(String value) {
            addCriterion("libType <", value, "libtype");
            return (Criteria) this;
        }

        public Criteria andLibtypeLessThanOrEqualTo(String value) {
            addCriterion("libType <=", value, "libtype");
            return (Criteria) this;
        }

        public Criteria andLibtypeLike(String value) {
            addCriterion("libType like", value, "libtype");
            return (Criteria) this;
        }

        public Criteria andLibtypeNotLike(String value) {
            addCriterion("libType not like", value, "libtype");
            return (Criteria) this;
        }

        public Criteria andLibtypeIn(List<String> values) {
            addCriterion("libType in", values, "libtype");
            return (Criteria) this;
        }

        public Criteria andLibtypeNotIn(List<String> values) {
            addCriterion("libType not in", values, "libtype");
            return (Criteria) this;
        }

        public Criteria andLibtypeBetween(String value1, String value2) {
            addCriterion("libType between", value1, value2, "libtype");
            return (Criteria) this;
        }

        public Criteria andLibtypeNotBetween(String value1, String value2) {
            addCriterion("libType not between", value1, value2, "libtype");
            return (Criteria) this;
        }

        public Criteria andConfirmindexIsNull() {
            addCriterion("confirmIndex is null");
            return (Criteria) this;
        }

        public Criteria andConfirmindexIsNotNull() {
            addCriterion("confirmIndex is not null");
            return (Criteria) this;
        }

        public Criteria andConfirmindexEqualTo(String value) {
            addCriterion("confirmIndex =", value, "confirmindex");
            return (Criteria) this;
        }

        public Criteria andConfirmindexNotEqualTo(String value) {
            addCriterion("confirmIndex <>", value, "confirmindex");
            return (Criteria) this;
        }

        public Criteria andConfirmindexGreaterThan(String value) {
            addCriterion("confirmIndex >", value, "confirmindex");
            return (Criteria) this;
        }

        public Criteria andConfirmindexGreaterThanOrEqualTo(String value) {
            addCriterion("confirmIndex >=", value, "confirmindex");
            return (Criteria) this;
        }

        public Criteria andConfirmindexLessThan(String value) {
            addCriterion("confirmIndex <", value, "confirmindex");
            return (Criteria) this;
        }

        public Criteria andConfirmindexLessThanOrEqualTo(String value) {
            addCriterion("confirmIndex <=", value, "confirmindex");
            return (Criteria) this;
        }

        public Criteria andConfirmindexLike(String value) {
            addCriterion("confirmIndex like", value, "confirmindex");
            return (Criteria) this;
        }

        public Criteria andConfirmindexNotLike(String value) {
            addCriterion("confirmIndex not like", value, "confirmindex");
            return (Criteria) this;
        }

        public Criteria andConfirmindexIn(List<String> values) {
            addCriterion("confirmIndex in", values, "confirmindex");
            return (Criteria) this;
        }

        public Criteria andConfirmindexNotIn(List<String> values) {
            addCriterion("confirmIndex not in", values, "confirmindex");
            return (Criteria) this;
        }

        public Criteria andConfirmindexBetween(String value1, String value2) {
            addCriterion("confirmIndex between", value1, value2, "confirmindex");
            return (Criteria) this;
        }

        public Criteria andConfirmindexNotBetween(String value1, String value2) {
            addCriterion("confirmIndex not between", value1, value2, "confirmindex");
            return (Criteria) this;
        }

        public Criteria andPeaksizeIsNull() {
            addCriterion("peaksize is null");
            return (Criteria) this;
        }

        public Criteria andPeaksizeIsNotNull() {
            addCriterion("peaksize is not null");
            return (Criteria) this;
        }

        public Criteria andPeaksizeEqualTo(String value) {
            addCriterion("peaksize =", value, "peaksize");
            return (Criteria) this;
        }

        public Criteria andPeaksizeNotEqualTo(String value) {
            addCriterion("peaksize <>", value, "peaksize");
            return (Criteria) this;
        }

        public Criteria andPeaksizeGreaterThan(String value) {
            addCriterion("peaksize >", value, "peaksize");
            return (Criteria) this;
        }

        public Criteria andPeaksizeGreaterThanOrEqualTo(String value) {
            addCriterion("peaksize >=", value, "peaksize");
            return (Criteria) this;
        }

        public Criteria andPeaksizeLessThan(String value) {
            addCriterion("peaksize <", value, "peaksize");
            return (Criteria) this;
        }

        public Criteria andPeaksizeLessThanOrEqualTo(String value) {
            addCriterion("peaksize <=", value, "peaksize");
            return (Criteria) this;
        }

        public Criteria andPeaksizeLike(String value) {
            addCriterion("peaksize like", value, "peaksize");
            return (Criteria) this;
        }

        public Criteria andPeaksizeNotLike(String value) {
            addCriterion("peaksize not like", value, "peaksize");
            return (Criteria) this;
        }

        public Criteria andPeaksizeIn(List<String> values) {
            addCriterion("peaksize in", values, "peaksize");
            return (Criteria) this;
        }

        public Criteria andPeaksizeNotIn(List<String> values) {
            addCriterion("peaksize not in", values, "peaksize");
            return (Criteria) this;
        }

        public Criteria andPeaksizeBetween(String value1, String value2) {
            addCriterion("peaksize between", value1, value2, "peaksize");
            return (Criteria) this;
        }

        public Criteria andPeaksizeNotBetween(String value1, String value2) {
            addCriterion("peaksize not between", value1, value2, "peaksize");
            return (Criteria) this;
        }

        public Criteria andQpcrIsNull() {
            addCriterion("qpcr is null");
            return (Criteria) this;
        }

        public Criteria andQpcrIsNotNull() {
            addCriterion("qpcr is not null");
            return (Criteria) this;
        }

        public Criteria andQpcrEqualTo(String value) {
            addCriterion("qpcr =", value, "qpcr");
            return (Criteria) this;
        }

        public Criteria andQpcrNotEqualTo(String value) {
            addCriterion("qpcr <>", value, "qpcr");
            return (Criteria) this;
        }

        public Criteria andQpcrGreaterThan(String value) {
            addCriterion("qpcr >", value, "qpcr");
            return (Criteria) this;
        }

        public Criteria andQpcrGreaterThanOrEqualTo(String value) {
            addCriterion("qpcr >=", value, "qpcr");
            return (Criteria) this;
        }

        public Criteria andQpcrLessThan(String value) {
            addCriterion("qpcr <", value, "qpcr");
            return (Criteria) this;
        }

        public Criteria andQpcrLessThanOrEqualTo(String value) {
            addCriterion("qpcr <=", value, "qpcr");
            return (Criteria) this;
        }

        public Criteria andQpcrLike(String value) {
            addCriterion("qpcr like", value, "qpcr");
            return (Criteria) this;
        }

        public Criteria andQpcrNotLike(String value) {
            addCriterion("qpcr not like", value, "qpcr");
            return (Criteria) this;
        }

        public Criteria andQpcrIn(List<String> values) {
            addCriterion("qpcr in", values, "qpcr");
            return (Criteria) this;
        }

        public Criteria andQpcrNotIn(List<String> values) {
            addCriterion("qpcr not in", values, "qpcr");
            return (Criteria) this;
        }

        public Criteria andQpcrBetween(String value1, String value2) {
            addCriterion("qpcr between", value1, value2, "qpcr");
            return (Criteria) this;
        }

        public Criteria andQpcrNotBetween(String value1, String value2) {
            addCriterion("qpcr not between", value1, value2, "qpcr");
            return (Criteria) this;
        }

        public Criteria andPeakdescIsNull() {
            addCriterion("peakDesc is null");
            return (Criteria) this;
        }

        public Criteria andPeakdescIsNotNull() {
            addCriterion("peakDesc is not null");
            return (Criteria) this;
        }

        public Criteria andPeakdescEqualTo(String value) {
            addCriterion("peakDesc =", value, "peakdesc");
            return (Criteria) this;
        }

        public Criteria andPeakdescNotEqualTo(String value) {
            addCriterion("peakDesc <>", value, "peakdesc");
            return (Criteria) this;
        }

        public Criteria andPeakdescGreaterThan(String value) {
            addCriterion("peakDesc >", value, "peakdesc");
            return (Criteria) this;
        }

        public Criteria andPeakdescGreaterThanOrEqualTo(String value) {
            addCriterion("peakDesc >=", value, "peakdesc");
            return (Criteria) this;
        }

        public Criteria andPeakdescLessThan(String value) {
            addCriterion("peakDesc <", value, "peakdesc");
            return (Criteria) this;
        }

        public Criteria andPeakdescLessThanOrEqualTo(String value) {
            addCriterion("peakDesc <=", value, "peakdesc");
            return (Criteria) this;
        }

        public Criteria andPeakdescLike(String value) {
            addCriterion("peakDesc like", value, "peakdesc");
            return (Criteria) this;
        }

        public Criteria andPeakdescNotLike(String value) {
            addCriterion("peakDesc not like", value, "peakdesc");
            return (Criteria) this;
        }

        public Criteria andPeakdescIn(List<String> values) {
            addCriterion("peakDesc in", values, "peakdesc");
            return (Criteria) this;
        }

        public Criteria andPeakdescNotIn(List<String> values) {
            addCriterion("peakDesc not in", values, "peakdesc");
            return (Criteria) this;
        }

        public Criteria andPeakdescBetween(String value1, String value2) {
            addCriterion("peakDesc between", value1, value2, "peakdesc");
            return (Criteria) this;
        }

        public Criteria andPeakdescNotBetween(String value1, String value2) {
            addCriterion("peakDesc not between", value1, value2, "peakdesc");
            return (Criteria) this;
        }

        public Criteria andLibcheckresultIsNull() {
            addCriterion("libCheckResult is null");
            return (Criteria) this;
        }

        public Criteria andLibcheckresultIsNotNull() {
            addCriterion("libCheckResult is not null");
            return (Criteria) this;
        }

        public Criteria andLibcheckresultEqualTo(String value) {
            addCriterion("libCheckResult =", value, "libcheckresult");
            return (Criteria) this;
        }

        public Criteria andLibcheckresultNotEqualTo(String value) {
            addCriterion("libCheckResult <>", value, "libcheckresult");
            return (Criteria) this;
        }

        public Criteria andLibcheckresultGreaterThan(String value) {
            addCriterion("libCheckResult >", value, "libcheckresult");
            return (Criteria) this;
        }

        public Criteria andLibcheckresultGreaterThanOrEqualTo(String value) {
            addCriterion("libCheckResult >=", value, "libcheckresult");
            return (Criteria) this;
        }

        public Criteria andLibcheckresultLessThan(String value) {
            addCriterion("libCheckResult <", value, "libcheckresult");
            return (Criteria) this;
        }

        public Criteria andLibcheckresultLessThanOrEqualTo(String value) {
            addCriterion("libCheckResult <=", value, "libcheckresult");
            return (Criteria) this;
        }

        public Criteria andLibcheckresultLike(String value) {
            addCriterion("libCheckResult like", value, "libcheckresult");
            return (Criteria) this;
        }

        public Criteria andLibcheckresultNotLike(String value) {
            addCriterion("libCheckResult not like", value, "libcheckresult");
            return (Criteria) this;
        }

        public Criteria andLibcheckresultIn(List<String> values) {
            addCriterion("libCheckResult in", values, "libcheckresult");
            return (Criteria) this;
        }

        public Criteria andLibcheckresultNotIn(List<String> values) {
            addCriterion("libCheckResult not in", values, "libcheckresult");
            return (Criteria) this;
        }

        public Criteria andLibcheckresultBetween(String value1, String value2) {
            addCriterion("libCheckResult between", value1, value2, "libcheckresult");
            return (Criteria) this;
        }

        public Criteria andLibcheckresultNotBetween(String value1, String value2) {
            addCriterion("libCheckResult not between", value1, value2, "libcheckresult");
            return (Criteria) this;
        }

        public Criteria andSeqmethodIsNull() {
            addCriterion("seqMethod is null");
            return (Criteria) this;
        }

        public Criteria andSeqmethodIsNotNull() {
            addCriterion("seqMethod is not null");
            return (Criteria) this;
        }

        public Criteria andSeqmethodEqualTo(String value) {
            addCriterion("seqMethod =", value, "seqmethod");
            return (Criteria) this;
        }

        public Criteria andSeqmethodNotEqualTo(String value) {
            addCriterion("seqMethod <>", value, "seqmethod");
            return (Criteria) this;
        }

        public Criteria andSeqmethodGreaterThan(String value) {
            addCriterion("seqMethod >", value, "seqmethod");
            return (Criteria) this;
        }

        public Criteria andSeqmethodGreaterThanOrEqualTo(String value) {
            addCriterion("seqMethod >=", value, "seqmethod");
            return (Criteria) this;
        }

        public Criteria andSeqmethodLessThan(String value) {
            addCriterion("seqMethod <", value, "seqmethod");
            return (Criteria) this;
        }

        public Criteria andSeqmethodLessThanOrEqualTo(String value) {
            addCriterion("seqMethod <=", value, "seqmethod");
            return (Criteria) this;
        }

        public Criteria andSeqmethodLike(String value) {
            addCriterion("seqMethod like", value, "seqmethod");
            return (Criteria) this;
        }

        public Criteria andSeqmethodNotLike(String value) {
            addCriterion("seqMethod not like", value, "seqmethod");
            return (Criteria) this;
        }

        public Criteria andSeqmethodIn(List<String> values) {
            addCriterion("seqMethod in", values, "seqmethod");
            return (Criteria) this;
        }

        public Criteria andSeqmethodNotIn(List<String> values) {
            addCriterion("seqMethod not in", values, "seqmethod");
            return (Criteria) this;
        }

        public Criteria andSeqmethodBetween(String value1, String value2) {
            addCriterion("seqMethod between", value1, value2, "seqmethod");
            return (Criteria) this;
        }

        public Criteria andSeqmethodNotBetween(String value1, String value2) {
            addCriterion("seqMethod not between", value1, value2, "seqmethod");
            return (Criteria) this;
        }

        public Criteria andUploadsizeIsNull() {
            addCriterion("uploadSize is null");
            return (Criteria) this;
        }

        public Criteria andUploadsizeIsNotNull() {
            addCriterion("uploadSize is not null");
            return (Criteria) this;
        }

        public Criteria andUploadsizeEqualTo(String value) {
            addCriterion("uploadSize =", value, "uploadsize");
            return (Criteria) this;
        }

        public Criteria andUploadsizeNotEqualTo(String value) {
            addCriterion("uploadSize <>", value, "uploadsize");
            return (Criteria) this;
        }

        public Criteria andUploadsizeGreaterThan(String value) {
            addCriterion("uploadSize >", value, "uploadsize");
            return (Criteria) this;
        }

        public Criteria andUploadsizeGreaterThanOrEqualTo(String value) {
            addCriterion("uploadSize >=", value, "uploadsize");
            return (Criteria) this;
        }

        public Criteria andUploadsizeLessThan(String value) {
            addCriterion("uploadSize <", value, "uploadsize");
            return (Criteria) this;
        }

        public Criteria andUploadsizeLessThanOrEqualTo(String value) {
            addCriterion("uploadSize <=", value, "uploadsize");
            return (Criteria) this;
        }

        public Criteria andUploadsizeLike(String value) {
            addCriterion("uploadSize like", value, "uploadsize");
            return (Criteria) this;
        }

        public Criteria andUploadsizeNotLike(String value) {
            addCriterion("uploadSize not like", value, "uploadsize");
            return (Criteria) this;
        }

        public Criteria andUploadsizeIn(List<String> values) {
            addCriterion("uploadSize in", values, "uploadsize");
            return (Criteria) this;
        }

        public Criteria andUploadsizeNotIn(List<String> values) {
            addCriterion("uploadSize not in", values, "uploadsize");
            return (Criteria) this;
        }

        public Criteria andUploadsizeBetween(String value1, String value2) {
            addCriterion("uploadSize between", value1, value2, "uploadsize");
            return (Criteria) this;
        }

        public Criteria andUploadsizeNotBetween(String value1, String value2) {
            addCriterion("uploadSize not between", value1, value2, "uploadsize");
            return (Criteria) this;
        }

        public Criteria andUploadunitIsNull() {
            addCriterion("uploadUnit is null");
            return (Criteria) this;
        }

        public Criteria andUploadunitIsNotNull() {
            addCriterion("uploadUnit is not null");
            return (Criteria) this;
        }

        public Criteria andUploadunitEqualTo(String value) {
            addCriterion("uploadUnit =", value, "uploadunit");
            return (Criteria) this;
        }

        public Criteria andUploadunitNotEqualTo(String value) {
            addCriterion("uploadUnit <>", value, "uploadunit");
            return (Criteria) this;
        }

        public Criteria andUploadunitGreaterThan(String value) {
            addCriterion("uploadUnit >", value, "uploadunit");
            return (Criteria) this;
        }

        public Criteria andUploadunitGreaterThanOrEqualTo(String value) {
            addCriterion("uploadUnit >=", value, "uploadunit");
            return (Criteria) this;
        }

        public Criteria andUploadunitLessThan(String value) {
            addCriterion("uploadUnit <", value, "uploadunit");
            return (Criteria) this;
        }

        public Criteria andUploadunitLessThanOrEqualTo(String value) {
            addCriterion("uploadUnit <=", value, "uploadunit");
            return (Criteria) this;
        }

        public Criteria andUploadunitLike(String value) {
            addCriterion("uploadUnit like", value, "uploadunit");
            return (Criteria) this;
        }

        public Criteria andUploadunitNotLike(String value) {
            addCriterion("uploadUnit not like", value, "uploadunit");
            return (Criteria) this;
        }

        public Criteria andUploadunitIn(List<String> values) {
            addCriterion("uploadUnit in", values, "uploadunit");
            return (Criteria) this;
        }

        public Criteria andUploadunitNotIn(List<String> values) {
            addCriterion("uploadUnit not in", values, "uploadunit");
            return (Criteria) this;
        }

        public Criteria andUploadunitBetween(String value1, String value2) {
            addCriterion("uploadUnit between", value1, value2, "uploadunit");
            return (Criteria) this;
        }

        public Criteria andUploadunitNotBetween(String value1, String value2) {
            addCriterion("uploadUnit not between", value1, value2, "uploadunit");
            return (Criteria) this;
        }

        public Criteria andUploadremarkIsNull() {
            addCriterion("uploadRemark is null");
            return (Criteria) this;
        }

        public Criteria andUploadremarkIsNotNull() {
            addCriterion("uploadRemark is not null");
            return (Criteria) this;
        }

        public Criteria andUploadremarkEqualTo(String value) {
            addCriterion("uploadRemark =", value, "uploadremark");
            return (Criteria) this;
        }

        public Criteria andUploadremarkNotEqualTo(String value) {
            addCriterion("uploadRemark <>", value, "uploadremark");
            return (Criteria) this;
        }

        public Criteria andUploadremarkGreaterThan(String value) {
            addCriterion("uploadRemark >", value, "uploadremark");
            return (Criteria) this;
        }

        public Criteria andUploadremarkGreaterThanOrEqualTo(String value) {
            addCriterion("uploadRemark >=", value, "uploadremark");
            return (Criteria) this;
        }

        public Criteria andUploadremarkLessThan(String value) {
            addCriterion("uploadRemark <", value, "uploadremark");
            return (Criteria) this;
        }

        public Criteria andUploadremarkLessThanOrEqualTo(String value) {
            addCriterion("uploadRemark <=", value, "uploadremark");
            return (Criteria) this;
        }

        public Criteria andUploadremarkLike(String value) {
            addCriterion("uploadRemark like", value, "uploadremark");
            return (Criteria) this;
        }

        public Criteria andUploadremarkNotLike(String value) {
            addCriterion("uploadRemark not like", value, "uploadremark");
            return (Criteria) this;
        }

        public Criteria andUploadremarkIn(List<String> values) {
            addCriterion("uploadRemark in", values, "uploadremark");
            return (Criteria) this;
        }

        public Criteria andUploadremarkNotIn(List<String> values) {
            addCriterion("uploadRemark not in", values, "uploadremark");
            return (Criteria) this;
        }

        public Criteria andUploadremarkBetween(String value1, String value2) {
            addCriterion("uploadRemark between", value1, value2, "uploadremark");
            return (Criteria) this;
        }

        public Criteria andUploadremarkNotBetween(String value1, String value2) {
            addCriterion("uploadRemark not between", value1, value2, "uploadremark");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNull() {
            addCriterion("creater is null");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNotNull() {
            addCriterion("creater is not null");
            return (Criteria) this;
        }

        public Criteria andCreaterEqualTo(String value) {
            addCriterion("creater =", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotEqualTo(String value) {
            addCriterion("creater <>", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThan(String value) {
            addCriterion("creater >", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThanOrEqualTo(String value) {
            addCriterion("creater >=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThan(String value) {
            addCriterion("creater <", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThanOrEqualTo(String value) {
            addCriterion("creater <=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLike(String value) {
            addCriterion("creater like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotLike(String value) {
            addCriterion("creater not like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterIn(List<String> values) {
            addCriterion("creater in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotIn(List<String> values) {
            addCriterion("creater not in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterBetween(String value1, String value2) {
            addCriterion("creater between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotBetween(String value1, String value2) {
            addCriterion("creater not between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andUpdateuserIsNull() {
            addCriterion("updateuser is null");
            return (Criteria) this;
        }

        public Criteria andUpdateuserIsNotNull() {
            addCriterion("updateuser is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateuserEqualTo(String value) {
            addCriterion("updateuser =", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserNotEqualTo(String value) {
            addCriterion("updateuser <>", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserGreaterThan(String value) {
            addCriterion("updateuser >", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserGreaterThanOrEqualTo(String value) {
            addCriterion("updateuser >=", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserLessThan(String value) {
            addCriterion("updateuser <", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserLessThanOrEqualTo(String value) {
            addCriterion("updateuser <=", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserLike(String value) {
            addCriterion("updateuser like", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserNotLike(String value) {
            addCriterion("updateuser not like", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserIn(List<String> values) {
            addCriterion("updateuser in", values, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserNotIn(List<String> values) {
            addCriterion("updateuser not in", values, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserBetween(String value1, String value2) {
            addCriterion("updateuser between", value1, value2, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserNotBetween(String value1, String value2) {
            addCriterion("updateuser not between", value1, value2, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterion("updateTime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterion("updateTime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterion("updateTime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updateTime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterion("updateTime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("updateTime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterion("updateTime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterion("updateTime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("updateTime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("updateTime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andRowindexIsNull() {
            addCriterion("rowIndex is null");
            return (Criteria) this;
        }

        public Criteria andRowindexIsNotNull() {
            addCriterion("rowIndex is not null");
            return (Criteria) this;
        }

        public Criteria andRowindexEqualTo(Integer value) {
            addCriterion("rowIndex =", value, "rowindex");
            return (Criteria) this;
        }

        public Criteria andRowindexNotEqualTo(Integer value) {
            addCriterion("rowIndex <>", value, "rowindex");
            return (Criteria) this;
        }

        public Criteria andRowindexGreaterThan(Integer value) {
            addCriterion("rowIndex >", value, "rowindex");
            return (Criteria) this;
        }

        public Criteria andRowindexGreaterThanOrEqualTo(Integer value) {
            addCriterion("rowIndex >=", value, "rowindex");
            return (Criteria) this;
        }

        public Criteria andRowindexLessThan(Integer value) {
            addCriterion("rowIndex <", value, "rowindex");
            return (Criteria) this;
        }

        public Criteria andRowindexLessThanOrEqualTo(Integer value) {
            addCriterion("rowIndex <=", value, "rowindex");
            return (Criteria) this;
        }

        public Criteria andRowindexIn(List<Integer> values) {
            addCriterion("rowIndex in", values, "rowindex");
            return (Criteria) this;
        }

        public Criteria andRowindexNotIn(List<Integer> values) {
            addCriterion("rowIndex not in", values, "rowindex");
            return (Criteria) this;
        }

        public Criteria andRowindexBetween(Integer value1, Integer value2) {
            addCriterion("rowIndex between", value1, value2, "rowindex");
            return (Criteria) this;
        }

        public Criteria andRowindexNotBetween(Integer value1, Integer value2) {
            addCriterion("rowIndex not between", value1, value2, "rowindex");
            return (Criteria) this;
        }

        public Criteria andCurrentstatuIsNull() {
            addCriterion("currentstatu is null");
            return (Criteria) this;
        }

        public Criteria andCurrentstatuIsNotNull() {
            addCriterion("currentstatu is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentstatuEqualTo(String value) {
            addCriterion("currentstatu =", value, "currentstatu");
            return (Criteria) this;
        }

        public Criteria andCurrentstatuNotEqualTo(String value) {
            addCriterion("currentstatu <>", value, "currentstatu");
            return (Criteria) this;
        }

        public Criteria andCurrentstatuGreaterThan(String value) {
            addCriterion("currentstatu >", value, "currentstatu");
            return (Criteria) this;
        }

        public Criteria andCurrentstatuGreaterThanOrEqualTo(String value) {
            addCriterion("currentstatu >=", value, "currentstatu");
            return (Criteria) this;
        }

        public Criteria andCurrentstatuLessThan(String value) {
            addCriterion("currentstatu <", value, "currentstatu");
            return (Criteria) this;
        }

        public Criteria andCurrentstatuLessThanOrEqualTo(String value) {
            addCriterion("currentstatu <=", value, "currentstatu");
            return (Criteria) this;
        }

        public Criteria andCurrentstatuLike(String value) {
            addCriterion("currentstatu like", value, "currentstatu");
            return (Criteria) this;
        }

        public Criteria andCurrentstatuNotLike(String value) {
            addCriterion("currentstatu not like", value, "currentstatu");
            return (Criteria) this;
        }

        public Criteria andCurrentstatuIn(List<String> values) {
            addCriterion("currentstatu in", values, "currentstatu");
            return (Criteria) this;
        }

        public Criteria andCurrentstatuNotIn(List<String> values) {
            addCriterion("currentstatu not in", values, "currentstatu");
            return (Criteria) this;
        }

        public Criteria andCurrentstatuBetween(String value1, String value2) {
            addCriterion("currentstatu between", value1, value2, "currentstatu");
            return (Criteria) this;
        }

        public Criteria andCurrentstatuNotBetween(String value1, String value2) {
            addCriterion("currentstatu not between", value1, value2, "currentstatu");
            return (Criteria) this;
        }

        public Criteria andSubidIsNull() {
            addCriterion("subId is null");
            return (Criteria) this;
        }

        public Criteria andSubidIsNotNull() {
            addCriterion("subId is not null");
            return (Criteria) this;
        }

        public Criteria andSubidEqualTo(String value) {
            addCriterion("subId =", value, "subid");
            return (Criteria) this;
        }

        public Criteria andSubidNotEqualTo(String value) {
            addCriterion("subId <>", value, "subid");
            return (Criteria) this;
        }

        public Criteria andSubidGreaterThan(String value) {
            addCriterion("subId >", value, "subid");
            return (Criteria) this;
        }

        public Criteria andSubidGreaterThanOrEqualTo(String value) {
            addCriterion("subId >=", value, "subid");
            return (Criteria) this;
        }

        public Criteria andSubidLessThan(String value) {
            addCriterion("subId <", value, "subid");
            return (Criteria) this;
        }

        public Criteria andSubidLessThanOrEqualTo(String value) {
            addCriterion("subId <=", value, "subid");
            return (Criteria) this;
        }

        public Criteria andSubidLike(String value) {
            addCriterion("subId like", value, "subid");
            return (Criteria) this;
        }

        public Criteria andSubidNotLike(String value) {
            addCriterion("subId not like", value, "subid");
            return (Criteria) this;
        }

        public Criteria andSubidIn(List<String> values) {
            addCriterion("subId in", values, "subid");
            return (Criteria) this;
        }

        public Criteria andSubidNotIn(List<String> values) {
            addCriterion("subId not in", values, "subid");
            return (Criteria) this;
        }

        public Criteria andSubidBetween(String value1, String value2) {
            addCriterion("subId between", value1, value2, "subid");
            return (Criteria) this;
        }

        public Criteria andSubidNotBetween(String value1, String value2) {
            addCriterion("subId not between", value1, value2, "subid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cibr_task_process_confirm
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cibr_task_process_confirm
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}