package com.cibr.animal.demo.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CibrSysEnvironmentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cibr_sys_environment
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cibr_sys_environment
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cibr_sys_environment
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_environment
     *
     * @mbggenerated
     */
    public CibrSysEnvironmentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_environment
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_environment
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_environment
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_environment
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_environment
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_environment
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_environment
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_environment
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_environment
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cibr_sys_environment
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cibr_sys_environment
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCultureDayIsNull() {
            addCriterion("culture_day is null");
            return (Criteria) this;
        }

        public Criteria andCultureDayIsNotNull() {
            addCriterion("culture_day is not null");
            return (Criteria) this;
        }

        public Criteria andCultureDayEqualTo(String value) {
            addCriterion("culture_day =", value, "cultureDay");
            return (Criteria) this;
        }

        public Criteria andCultureDayNotEqualTo(String value) {
            addCriterion("culture_day <>", value, "cultureDay");
            return (Criteria) this;
        }

        public Criteria andCultureDayGreaterThan(String value) {
            addCriterion("culture_day >", value, "cultureDay");
            return (Criteria) this;
        }

        public Criteria andCultureDayGreaterThanOrEqualTo(String value) {
            addCriterion("culture_day >=", value, "cultureDay");
            return (Criteria) this;
        }

        public Criteria andCultureDayLessThan(String value) {
            addCriterion("culture_day <", value, "cultureDay");
            return (Criteria) this;
        }

        public Criteria andCultureDayLessThanOrEqualTo(String value) {
            addCriterion("culture_day <=", value, "cultureDay");
            return (Criteria) this;
        }

        public Criteria andCultureDayLike(String value) {
            addCriterion("culture_day like", value, "cultureDay");
            return (Criteria) this;
        }

        public Criteria andCultureDayNotLike(String value) {
            addCriterion("culture_day not like", value, "cultureDay");
            return (Criteria) this;
        }

        public Criteria andCultureDayIn(List<String> values) {
            addCriterion("culture_day in", values, "cultureDay");
            return (Criteria) this;
        }

        public Criteria andCultureDayNotIn(List<String> values) {
            addCriterion("culture_day not in", values, "cultureDay");
            return (Criteria) this;
        }

        public Criteria andCultureDayBetween(String value1, String value2) {
            addCriterion("culture_day between", value1, value2, "cultureDay");
            return (Criteria) this;
        }

        public Criteria andCultureDayNotBetween(String value1, String value2) {
            addCriterion("culture_day not between", value1, value2, "cultureDay");
            return (Criteria) this;
        }

        public Criteria andCultureTempIsNull() {
            addCriterion("culture_temp is null");
            return (Criteria) this;
        }

        public Criteria andCultureTempIsNotNull() {
            addCriterion("culture_temp is not null");
            return (Criteria) this;
        }

        public Criteria andCultureTempEqualTo(String value) {
            addCriterion("culture_temp =", value, "cultureTemp");
            return (Criteria) this;
        }

        public Criteria andCultureTempNotEqualTo(String value) {
            addCriterion("culture_temp <>", value, "cultureTemp");
            return (Criteria) this;
        }

        public Criteria andCultureTempGreaterThan(String value) {
            addCriterion("culture_temp >", value, "cultureTemp");
            return (Criteria) this;
        }

        public Criteria andCultureTempGreaterThanOrEqualTo(String value) {
            addCriterion("culture_temp >=", value, "cultureTemp");
            return (Criteria) this;
        }

        public Criteria andCultureTempLessThan(String value) {
            addCriterion("culture_temp <", value, "cultureTemp");
            return (Criteria) this;
        }

        public Criteria andCultureTempLessThanOrEqualTo(String value) {
            addCriterion("culture_temp <=", value, "cultureTemp");
            return (Criteria) this;
        }

        public Criteria andCultureTempLike(String value) {
            addCriterion("culture_temp like", value, "cultureTemp");
            return (Criteria) this;
        }

        public Criteria andCultureTempNotLike(String value) {
            addCriterion("culture_temp not like", value, "cultureTemp");
            return (Criteria) this;
        }

        public Criteria andCultureTempIn(List<String> values) {
            addCriterion("culture_temp in", values, "cultureTemp");
            return (Criteria) this;
        }

        public Criteria andCultureTempNotIn(List<String> values) {
            addCriterion("culture_temp not in", values, "cultureTemp");
            return (Criteria) this;
        }

        public Criteria andCultureTempBetween(String value1, String value2) {
            addCriterion("culture_temp between", value1, value2, "cultureTemp");
            return (Criteria) this;
        }

        public Criteria andCultureTempNotBetween(String value1, String value2) {
            addCriterion("culture_temp not between", value1, value2, "cultureTemp");
            return (Criteria) this;
        }

        public Criteria andCultureHumIsNull() {
            addCriterion("culture_hum is null");
            return (Criteria) this;
        }

        public Criteria andCultureHumIsNotNull() {
            addCriterion("culture_hum is not null");
            return (Criteria) this;
        }

        public Criteria andCultureHumEqualTo(String value) {
            addCriterion("culture_hum =", value, "cultureHum");
            return (Criteria) this;
        }

        public Criteria andCultureHumNotEqualTo(String value) {
            addCriterion("culture_hum <>", value, "cultureHum");
            return (Criteria) this;
        }

        public Criteria andCultureHumGreaterThan(String value) {
            addCriterion("culture_hum >", value, "cultureHum");
            return (Criteria) this;
        }

        public Criteria andCultureHumGreaterThanOrEqualTo(String value) {
            addCriterion("culture_hum >=", value, "cultureHum");
            return (Criteria) this;
        }

        public Criteria andCultureHumLessThan(String value) {
            addCriterion("culture_hum <", value, "cultureHum");
            return (Criteria) this;
        }

        public Criteria andCultureHumLessThanOrEqualTo(String value) {
            addCriterion("culture_hum <=", value, "cultureHum");
            return (Criteria) this;
        }

        public Criteria andCultureHumLike(String value) {
            addCriterion("culture_hum like", value, "cultureHum");
            return (Criteria) this;
        }

        public Criteria andCultureHumNotLike(String value) {
            addCriterion("culture_hum not like", value, "cultureHum");
            return (Criteria) this;
        }

        public Criteria andCultureHumIn(List<String> values) {
            addCriterion("culture_hum in", values, "cultureHum");
            return (Criteria) this;
        }

        public Criteria andCultureHumNotIn(List<String> values) {
            addCriterion("culture_hum not in", values, "cultureHum");
            return (Criteria) this;
        }

        public Criteria andCultureHumBetween(String value1, String value2) {
            addCriterion("culture_hum between", value1, value2, "cultureHum");
            return (Criteria) this;
        }

        public Criteria andCultureHumNotBetween(String value1, String value2) {
            addCriterion("culture_hum not between", value1, value2, "cultureHum");
            return (Criteria) this;
        }

        public Criteria andCultureLigIsNull() {
            addCriterion("culture_lig is null");
            return (Criteria) this;
        }

        public Criteria andCultureLigIsNotNull() {
            addCriterion("culture_lig is not null");
            return (Criteria) this;
        }

        public Criteria andCultureLigEqualTo(String value) {
            addCriterion("culture_lig =", value, "cultureLig");
            return (Criteria) this;
        }

        public Criteria andCultureLigNotEqualTo(String value) {
            addCriterion("culture_lig <>", value, "cultureLig");
            return (Criteria) this;
        }

        public Criteria andCultureLigGreaterThan(String value) {
            addCriterion("culture_lig >", value, "cultureLig");
            return (Criteria) this;
        }

        public Criteria andCultureLigGreaterThanOrEqualTo(String value) {
            addCriterion("culture_lig >=", value, "cultureLig");
            return (Criteria) this;
        }

        public Criteria andCultureLigLessThan(String value) {
            addCriterion("culture_lig <", value, "cultureLig");
            return (Criteria) this;
        }

        public Criteria andCultureLigLessThanOrEqualTo(String value) {
            addCriterion("culture_lig <=", value, "cultureLig");
            return (Criteria) this;
        }

        public Criteria andCultureLigLike(String value) {
            addCriterion("culture_lig like", value, "cultureLig");
            return (Criteria) this;
        }

        public Criteria andCultureLigNotLike(String value) {
            addCriterion("culture_lig not like", value, "cultureLig");
            return (Criteria) this;
        }

        public Criteria andCultureLigIn(List<String> values) {
            addCriterion("culture_lig in", values, "cultureLig");
            return (Criteria) this;
        }

        public Criteria andCultureLigNotIn(List<String> values) {
            addCriterion("culture_lig not in", values, "cultureLig");
            return (Criteria) this;
        }

        public Criteria andCultureLigBetween(String value1, String value2) {
            addCriterion("culture_lig between", value1, value2, "cultureLig");
            return (Criteria) this;
        }

        public Criteria andCultureLigNotBetween(String value1, String value2) {
            addCriterion("culture_lig not between", value1, value2, "cultureLig");
            return (Criteria) this;
        }

        public Criteria andCulture1IsNull() {
            addCriterion("culture_1 is null");
            return (Criteria) this;
        }

        public Criteria andCulture1IsNotNull() {
            addCriterion("culture_1 is not null");
            return (Criteria) this;
        }

        public Criteria andCulture1EqualTo(String value) {
            addCriterion("culture_1 =", value, "culture1");
            return (Criteria) this;
        }

        public Criteria andCulture1NotEqualTo(String value) {
            addCriterion("culture_1 <>", value, "culture1");
            return (Criteria) this;
        }

        public Criteria andCulture1GreaterThan(String value) {
            addCriterion("culture_1 >", value, "culture1");
            return (Criteria) this;
        }

        public Criteria andCulture1GreaterThanOrEqualTo(String value) {
            addCriterion("culture_1 >=", value, "culture1");
            return (Criteria) this;
        }

        public Criteria andCulture1LessThan(String value) {
            addCriterion("culture_1 <", value, "culture1");
            return (Criteria) this;
        }

        public Criteria andCulture1LessThanOrEqualTo(String value) {
            addCriterion("culture_1 <=", value, "culture1");
            return (Criteria) this;
        }

        public Criteria andCulture1Like(String value) {
            addCriterion("culture_1 like", value, "culture1");
            return (Criteria) this;
        }

        public Criteria andCulture1NotLike(String value) {
            addCriterion("culture_1 not like", value, "culture1");
            return (Criteria) this;
        }

        public Criteria andCulture1In(List<String> values) {
            addCriterion("culture_1 in", values, "culture1");
            return (Criteria) this;
        }

        public Criteria andCulture1NotIn(List<String> values) {
            addCriterion("culture_1 not in", values, "culture1");
            return (Criteria) this;
        }

        public Criteria andCulture1Between(String value1, String value2) {
            addCriterion("culture_1 between", value1, value2, "culture1");
            return (Criteria) this;
        }

        public Criteria andCulture1NotBetween(String value1, String value2) {
            addCriterion("culture_1 not between", value1, value2, "culture1");
            return (Criteria) this;
        }

        public Criteria andCulture2IsNull() {
            addCriterion("culture_2 is null");
            return (Criteria) this;
        }

        public Criteria andCulture2IsNotNull() {
            addCriterion("culture_2 is not null");
            return (Criteria) this;
        }

        public Criteria andCulture2EqualTo(String value) {
            addCriterion("culture_2 =", value, "culture2");
            return (Criteria) this;
        }

        public Criteria andCulture2NotEqualTo(String value) {
            addCriterion("culture_2 <>", value, "culture2");
            return (Criteria) this;
        }

        public Criteria andCulture2GreaterThan(String value) {
            addCriterion("culture_2 >", value, "culture2");
            return (Criteria) this;
        }

        public Criteria andCulture2GreaterThanOrEqualTo(String value) {
            addCriterion("culture_2 >=", value, "culture2");
            return (Criteria) this;
        }

        public Criteria andCulture2LessThan(String value) {
            addCriterion("culture_2 <", value, "culture2");
            return (Criteria) this;
        }

        public Criteria andCulture2LessThanOrEqualTo(String value) {
            addCriterion("culture_2 <=", value, "culture2");
            return (Criteria) this;
        }

        public Criteria andCulture2Like(String value) {
            addCriterion("culture_2 like", value, "culture2");
            return (Criteria) this;
        }

        public Criteria andCulture2NotLike(String value) {
            addCriterion("culture_2 not like", value, "culture2");
            return (Criteria) this;
        }

        public Criteria andCulture2In(List<String> values) {
            addCriterion("culture_2 in", values, "culture2");
            return (Criteria) this;
        }

        public Criteria andCulture2NotIn(List<String> values) {
            addCriterion("culture_2 not in", values, "culture2");
            return (Criteria) this;
        }

        public Criteria andCulture2Between(String value1, String value2) {
            addCriterion("culture_2 between", value1, value2, "culture2");
            return (Criteria) this;
        }

        public Criteria andCulture2NotBetween(String value1, String value2) {
            addCriterion("culture_2 not between", value1, value2, "culture2");
            return (Criteria) this;
        }

        public Criteria andCulture3IsNull() {
            addCriterion("culture_3 is null");
            return (Criteria) this;
        }

        public Criteria andCulture3IsNotNull() {
            addCriterion("culture_3 is not null");
            return (Criteria) this;
        }

        public Criteria andCulture3EqualTo(String value) {
            addCriterion("culture_3 =", value, "culture3");
            return (Criteria) this;
        }

        public Criteria andCulture3NotEqualTo(String value) {
            addCriterion("culture_3 <>", value, "culture3");
            return (Criteria) this;
        }

        public Criteria andCulture3GreaterThan(String value) {
            addCriterion("culture_3 >", value, "culture3");
            return (Criteria) this;
        }

        public Criteria andCulture3GreaterThanOrEqualTo(String value) {
            addCriterion("culture_3 >=", value, "culture3");
            return (Criteria) this;
        }

        public Criteria andCulture3LessThan(String value) {
            addCriterion("culture_3 <", value, "culture3");
            return (Criteria) this;
        }

        public Criteria andCulture3LessThanOrEqualTo(String value) {
            addCriterion("culture_3 <=", value, "culture3");
            return (Criteria) this;
        }

        public Criteria andCulture3Like(String value) {
            addCriterion("culture_3 like", value, "culture3");
            return (Criteria) this;
        }

        public Criteria andCulture3NotLike(String value) {
            addCriterion("culture_3 not like", value, "culture3");
            return (Criteria) this;
        }

        public Criteria andCulture3In(List<String> values) {
            addCriterion("culture_3 in", values, "culture3");
            return (Criteria) this;
        }

        public Criteria andCulture3NotIn(List<String> values) {
            addCriterion("culture_3 not in", values, "culture3");
            return (Criteria) this;
        }

        public Criteria andCulture3Between(String value1, String value2) {
            addCriterion("culture_3 between", value1, value2, "culture3");
            return (Criteria) this;
        }

        public Criteria andCulture3NotBetween(String value1, String value2) {
            addCriterion("culture_3 not between", value1, value2, "culture3");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andDisplaynameIsNull() {
            addCriterion("displayName is null");
            return (Criteria) this;
        }

        public Criteria andDisplaynameIsNotNull() {
            addCriterion("displayName is not null");
            return (Criteria) this;
        }

        public Criteria andDisplaynameEqualTo(String value) {
            addCriterion("displayName =", value, "displayname");
            return (Criteria) this;
        }

        public Criteria andDisplaynameNotEqualTo(String value) {
            addCriterion("displayName <>", value, "displayname");
            return (Criteria) this;
        }

        public Criteria andDisplaynameGreaterThan(String value) {
            addCriterion("displayName >", value, "displayname");
            return (Criteria) this;
        }

        public Criteria andDisplaynameGreaterThanOrEqualTo(String value) {
            addCriterion("displayName >=", value, "displayname");
            return (Criteria) this;
        }

        public Criteria andDisplaynameLessThan(String value) {
            addCriterion("displayName <", value, "displayname");
            return (Criteria) this;
        }

        public Criteria andDisplaynameLessThanOrEqualTo(String value) {
            addCriterion("displayName <=", value, "displayname");
            return (Criteria) this;
        }

        public Criteria andDisplaynameLike(String value) {
            addCriterion("displayName like", value, "displayname");
            return (Criteria) this;
        }

        public Criteria andDisplaynameNotLike(String value) {
            addCriterion("displayName not like", value, "displayname");
            return (Criteria) this;
        }

        public Criteria andDisplaynameIn(List<String> values) {
            addCriterion("displayName in", values, "displayname");
            return (Criteria) this;
        }

        public Criteria andDisplaynameNotIn(List<String> values) {
            addCriterion("displayName not in", values, "displayname");
            return (Criteria) this;
        }

        public Criteria andDisplaynameBetween(String value1, String value2) {
            addCriterion("displayName between", value1, value2, "displayname");
            return (Criteria) this;
        }

        public Criteria andDisplaynameNotBetween(String value1, String value2) {
            addCriterion("displayName not between", value1, value2, "displayname");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cibr_sys_environment
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cibr_sys_environment
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}