package com.cibr.animal.demo.entity;

import java.util.Date;

public class CibrTaskAskPrepare {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_ask_prepare.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_ask_prepare.handler
     *
     * @mbggenerated
     */
    private String handler;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_ask_prepare.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_ask_prepare.needmore
     *
     * @mbggenerated
     */
    private String needmore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_ask_prepare.startTime
     *
     * @mbggenerated
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_ask_prepare.endTime
     *
     * @mbggenerated
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_ask_prepare.remarks1
     *
     * @mbggenerated
     */
    private String remarks1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_ask_prepare.completeTime
     *
     * @mbggenerated
     */
    private Date completetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_ask_prepare.realnumber
     *
     * @mbggenerated
     */
    private String realnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_ask_prepare.realage
     *
     * @mbggenerated
     */
    private String realage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_ask_prepare.realexpTime
     *
     * @mbggenerated
     */
    private Date realexptime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_ask_prepare.reamrks2
     *
     * @mbggenerated
     */
    private String reamrks2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_ask_prepare.updateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_ask_prepare.updateUser
     *
     * @mbggenerated
     */
    private String updateuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_ask_prepare.askid
     *
     * @mbggenerated
     */
    private String askid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_ask_prepare.detailId
     *
     * @mbggenerated
     */
    private String detailid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_ask_prepare.prestatu
     *
     * @mbggenerated
     */
    private String prestatu;

    private CibrAnimalDrosophila animal;

    private CibrTaskDetailDrosophila detail;

    public CibrTaskDetailDrosophila getDetail() {
        return detail;
    }

    public void setDetail(CibrTaskDetailDrosophila detail) {
        this.detail = detail;
    }

    public CibrAnimalDrosophila getAnimal() {
        return animal;
    }

    public void setAnimal(CibrAnimalDrosophila animal) {
        this.animal = animal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_ask_prepare.id
     *
     * @return the value of cibr_task_ask_prepare.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_ask_prepare.id
     *
     * @param id the value for cibr_task_ask_prepare.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_ask_prepare.handler
     *
     * @return the value of cibr_task_ask_prepare.handler
     *
     * @mbggenerated
     */
    public String getHandler() {
        return handler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_ask_prepare.handler
     *
     * @param handler the value for cibr_task_ask_prepare.handler
     *
     * @mbggenerated
     */
    public void setHandler(String handler) {
        this.handler = handler == null ? null : handler.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_ask_prepare.createTime
     *
     * @return the value of cibr_task_ask_prepare.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_ask_prepare.createTime
     *
     * @param createtime the value for cibr_task_ask_prepare.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_ask_prepare.needmore
     *
     * @return the value of cibr_task_ask_prepare.needmore
     *
     * @mbggenerated
     */
    public String getNeedmore() {
        return needmore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_ask_prepare.needmore
     *
     * @param needmore the value for cibr_task_ask_prepare.needmore
     *
     * @mbggenerated
     */
    public void setNeedmore(String needmore) {
        this.needmore = needmore == null ? null : needmore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_ask_prepare.startTime
     *
     * @return the value of cibr_task_ask_prepare.startTime
     *
     * @mbggenerated
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_ask_prepare.startTime
     *
     * @param starttime the value for cibr_task_ask_prepare.startTime
     *
     * @mbggenerated
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_ask_prepare.endTime
     *
     * @return the value of cibr_task_ask_prepare.endTime
     *
     * @mbggenerated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_ask_prepare.endTime
     *
     * @param endtime the value for cibr_task_ask_prepare.endTime
     *
     * @mbggenerated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_ask_prepare.remarks1
     *
     * @return the value of cibr_task_ask_prepare.remarks1
     *
     * @mbggenerated
     */
    public String getRemarks1() {
        return remarks1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_ask_prepare.remarks1
     *
     * @param remarks1 the value for cibr_task_ask_prepare.remarks1
     *
     * @mbggenerated
     */
    public void setRemarks1(String remarks1) {
        this.remarks1 = remarks1 == null ? null : remarks1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_ask_prepare.completeTime
     *
     * @return the value of cibr_task_ask_prepare.completeTime
     *
     * @mbggenerated
     */
    public Date getCompletetime() {
        return completetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_ask_prepare.completeTime
     *
     * @param completetime the value for cibr_task_ask_prepare.completeTime
     *
     * @mbggenerated
     */
    public void setCompletetime(Date completetime) {
        this.completetime = completetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_ask_prepare.realnumber
     *
     * @return the value of cibr_task_ask_prepare.realnumber
     *
     * @mbggenerated
     */
    public String getRealnumber() {
        return realnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_ask_prepare.realnumber
     *
     * @param realnumber the value for cibr_task_ask_prepare.realnumber
     *
     * @mbggenerated
     */
    public void setRealnumber(String realnumber) {
        this.realnumber = realnumber == null ? null : realnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_ask_prepare.realage
     *
     * @return the value of cibr_task_ask_prepare.realage
     *
     * @mbggenerated
     */
    public String getRealage() {
        return realage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_ask_prepare.realage
     *
     * @param realage the value for cibr_task_ask_prepare.realage
     *
     * @mbggenerated
     */
    public void setRealage(String realage) {
        this.realage = realage == null ? null : realage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_ask_prepare.realexpTime
     *
     * @return the value of cibr_task_ask_prepare.realexpTime
     *
     * @mbggenerated
     */
    public Date getRealexptime() {
        return realexptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_ask_prepare.realexpTime
     *
     * @param realexptime the value for cibr_task_ask_prepare.realexpTime
     *
     * @mbggenerated
     */
    public void setRealexptime(Date realexptime) {
        this.realexptime = realexptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_ask_prepare.reamrks2
     *
     * @return the value of cibr_task_ask_prepare.reamrks2
     *
     * @mbggenerated
     */
    public String getReamrks2() {
        return reamrks2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_ask_prepare.reamrks2
     *
     * @param reamrks2 the value for cibr_task_ask_prepare.reamrks2
     *
     * @mbggenerated
     */
    public void setReamrks2(String reamrks2) {
        this.reamrks2 = reamrks2 == null ? null : reamrks2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_ask_prepare.updateTime
     *
     * @return the value of cibr_task_ask_prepare.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_ask_prepare.updateTime
     *
     * @param updatetime the value for cibr_task_ask_prepare.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_ask_prepare.updateUser
     *
     * @return the value of cibr_task_ask_prepare.updateUser
     *
     * @mbggenerated
     */
    public String getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_ask_prepare.updateUser
     *
     * @param updateuser the value for cibr_task_ask_prepare.updateUser
     *
     * @mbggenerated
     */
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser == null ? null : updateuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_ask_prepare.askid
     *
     * @return the value of cibr_task_ask_prepare.askid
     *
     * @mbggenerated
     */
    public String getAskid() {
        return askid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_ask_prepare.askid
     *
     * @param askid the value for cibr_task_ask_prepare.askid
     *
     * @mbggenerated
     */
    public void setAskid(String askid) {
        this.askid = askid == null ? null : askid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_ask_prepare.detailId
     *
     * @return the value of cibr_task_ask_prepare.detailId
     *
     * @mbggenerated
     */
    public String getDetailid() {
        return detailid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_ask_prepare.detailId
     *
     * @param detailid the value for cibr_task_ask_prepare.detailId
     *
     * @mbggenerated
     */
    public void setDetailid(String detailid) {
        this.detailid = detailid == null ? null : detailid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_ask_prepare.prestatu
     *
     * @return the value of cibr_task_ask_prepare.prestatu
     *
     * @mbggenerated
     */
    public String getPrestatu() {
        return prestatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_ask_prepare.prestatu
     *
     * @param prestatu the value for cibr_task_ask_prepare.prestatu
     *
     * @mbggenerated
     */
    public void setPrestatu(String prestatu) {
        this.prestatu = prestatu == null ? null : prestatu.trim();
    }
}