package com.cibr.animal.demo.entity;

import java.util.Date;

public class CibrTaskAskConfirm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_ask_confirm.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_ask_confirm.prepareid
     *
     * @mbggenerated
     */
    private String prepareid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_ask_confirm.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_ask_confirm.creater
     *
     * @mbggenerated
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_ask_confirm.isComplete
     *
     * @mbggenerated
     */
    private String iscomplete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cibr_task_ask_confirm.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_ask_confirm.id
     *
     * @return the value of cibr_task_ask_confirm.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_ask_confirm.id
     *
     * @param id the value for cibr_task_ask_confirm.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_ask_confirm.prepareid
     *
     * @return the value of cibr_task_ask_confirm.prepareid
     *
     * @mbggenerated
     */
    public String getPrepareid() {
        return prepareid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_ask_confirm.prepareid
     *
     * @param prepareid the value for cibr_task_ask_confirm.prepareid
     *
     * @mbggenerated
     */
    public void setPrepareid(String prepareid) {
        this.prepareid = prepareid == null ? null : prepareid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_ask_confirm.createTime
     *
     * @return the value of cibr_task_ask_confirm.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_ask_confirm.createTime
     *
     * @param createtime the value for cibr_task_ask_confirm.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_ask_confirm.creater
     *
     * @return the value of cibr_task_ask_confirm.creater
     *
     * @mbggenerated
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_ask_confirm.creater
     *
     * @param creater the value for cibr_task_ask_confirm.creater
     *
     * @mbggenerated
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_ask_confirm.isComplete
     *
     * @return the value of cibr_task_ask_confirm.isComplete
     *
     * @mbggenerated
     */
    public String getIscomplete() {
        return iscomplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_ask_confirm.isComplete
     *
     * @param iscomplete the value for cibr_task_ask_confirm.isComplete
     *
     * @mbggenerated
     */
    public void setIscomplete(String iscomplete) {
        this.iscomplete = iscomplete == null ? null : iscomplete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cibr_task_ask_confirm.remarks
     *
     * @return the value of cibr_task_ask_confirm.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cibr_task_ask_confirm.remarks
     *
     * @param remarks the value for cibr_task_ask_confirm.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}